### ISSUE TITLE
Tallyarbiter doesn't show up in Companion

### ISSUE THREAD

**Issue by DachsbauTV** [josephdadams/TallyArbiter#10]
Hi I can't seem to find the tallyarbiter module in Companion, just the ProTally

Thanks for the amazing work with the arbiter!

**Comment by josephdadams** [comment]
Thank you! Make sure you are on the latest beta release of Companion 2.1 if you want to use the Tally Arbiter module. :)

**Comment by DachsbauTV** [comment]
Found it, Thanks!

Sorry I have to ask another stupid question: How can i save the my settings of the arbiter? Everytime i reboot my PC everything is gone and I don't see a config.json in the folder?

**Comment by josephdadams** [comment]
It's possible an error is occurring writing the config file to the disk. Try running the terminal/command prompt window as an administrator and see if that helps!

**Comment by DachsbauTV** [comment]
I've tried it a couple of times now, also with reboots in-between and it still couldn't create the config file unfortunately.

The application itself works fine.

**Comment by DachsbauTV** [comment]
Could you maybe provide a default config.json which i can copy into the folder?

**Comment by josephdadams** [comment]
[config.json.zip](https://github.com/josephdadams/TallyArbiter/files/5278404/config.json.zip)

**Comment by DachsbauTV** [comment]
Thanks so much! It actually worked. Really excited to put it to use now

**Comment by josephdadams** [comment]
Awesome!
