### ISSUE TITLE
Tally from OBS with Sources using nested scenes

### ISSUE THREAD

**Issue by jmcc94** [josephdadams/TallyArbiter#107]
Is the expected behavior that sources within nested scenes within OBS won't be able to be used for Tally?

All my 'output' scenes within OBS are made up of nested scenes, which have the sources within them. These sources are used within multiple higher level nested scenes.

When I set up one of my sources as a TallyArbiter devices, it never shows as PVW ot PGM. If I use the 'output scene' then everything works well, except that I would now need to have a lot of these scenes added as TallyArbiter devices.

Is this expected behavior? If so, could a change be made to enable use of TallyArbiter with nested scenes within OBS?

**Comment by MatteoGheza** [comment]
@josephdadams I think we can implement this before the next release

**Comment by MatteoGheza** [comment]
I think we should check [sources list](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sources)

**Comment by jmcc94** [comment]
I think the GetSourceActive request will allow this to work.

**Comment by jmcc94** [comment]
@MatteoGheza - Any joy with testing this?

**Comment by gohamstergo** [comment]
not sure if its helpful, but the Bitfocus Companion OBS module handles tally (they call it "Feedback") very well for scenes, sources, and scenes-as-sources (nested). might be worth a look.
https://github.com/bitfocus/companion-module-obs-studio

**Comment by MatteoGheza** [comment]
@jmcc94 I'm sorry, I'm late.
Today I added the requested feature and I added support for VirtualCam and ReplayBuffer.
Besides, now TallyArbiter loads OBS sources status (if they are in preview or in program) at the start.
These contributions are in a bigger pull request, that includes lots of features and improvements.
I'll close this issue only when we release a version with these features.
