### ISSUE TITLE
npm publish not working

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#108]
@hrueger npm publishing does not seem to be working. Just thought I would ping you about it before I look into it, you may know more about it.

**Comment by josephdadams** [comment]
fwiw the docker action doesn't seem to be publishing either.

**Comment by hrueger** [comment]
Did you create a new version and therefore a new tag? You cannot override versions on npm, so we only push on git tags.

**Comment by josephdadams** [comment]
Ah. Forgot that. Was thinking when I pushed to master it would be doing this. Sorry!

**Comment by hrueger** [comment]
No problem. By only creating new releases on tags, you can Shop multiple new features / PRs in a single release.

**Comment by josephdadams** [comment]
Makes sense.
