### ISSUE TITLE
No way to disable chat mode in v2?

### ISSUE THREAD

**Issue by Baylink-gh** [josephdadams/TallyArbiter#111]
When I tested with v1.5 earlier in the year, there was a way to turn off the chat window in Web-client tallies.  I can't find that control in v2.02; was it dropped?

My use case is 3" Android phones facing both directions atop my cameras; I might want any particular one to default chat on or off, though it might also be nice to have it switchable at the display end.

**Comment by hrueger** [comment]
Did you try adding `?chat=false` to the url? It is documented here: https://josephdadams.github.io/TallyArbiter/docs/usage/sections/listener-clients

**Comment by Baylink-gh** [comment]
I had not, but I didn't remember having to do it by hand in 1.5 either.  Thanks for the pointer.

I'm still doing battle with the old browsers on these old phones...

**Comment by josephdadams** [comment]
@Baylink-gh if chat=false doesn’t work, reopen this. Thanks!
