### ISSUE TITLE
Add RossTalk compatibility to Actions

### ISSUE THREAD

**Issue by Appraxa** [josephdadams/TallyArbiter#114]
Hello,

I noticed that using the generic TCP when taking my LA1 device to PGM didn't send the RossTalk command over the network. I sent the TCP string "cc play" to port (7788) with a line feed (\n), but it seems like my Resi decoder isn't taking the TCP string.

I also realize that I may not seem like I know what I'm talking about, since I don't for the most part. Relatively new to the TCP/IP thing.

**Comment by Baylink-gh** [comment]
I have a bit set that strings on TCP streams need to end in CRLF, though I don't know if it specifically applies here.  Is that EOL user-changeable?

**Comment by josephdadams** [comment]
TA supports sending different EOL characters. So I'm 99% sure you could just send your TCP string to the RossTalk port and it would work if you sent CRLF at the end. I just haven't had time to test it so this remains open. That's all RossTalk is, TCP Strings.

**Comment by Appraxa** [comment]
I can verify that sending "cc play" over port 7788 when the program bus is active does not trigger RossTalk on the LA1 decoders.. I'm contacting Resi as well to see if they have any ideas. To my knowledge, the EOL isn't user changeable. Resi just  includes a software switch that engages and disengages RossTalk in their UI.

**Comment by JTF4** [comment]
It may be an issue there the decoder is not accepting RossTalk for some reason. 

Let's to a quick test and see if it's actually taking RossTalk. 

If you're on a mac:
1) Open terminal
2) Run `nc <ip of your decoder> 7788`
3) Once it connects put `cc play\r\n` and see if it plays

If you're on a windows computer:
1) open command prompt
2) Run `telet <ip of your decoder> 7788`
3) Once it connects put `cc play\r\n` and see if it plays

**Comment by JTF4** [comment]
I just realized that merging that would close the issue, so I unlinked it. 

However, If you look at #136 I did add direct support for RossTalk

**Comment by Appraxa** [comment]
My companion app works with the decoder, but I also verified that I can run the decoder over terminal from the same computer that is running TA. Just to make sure.. these are the correct actions?

<img width="781" alt="Screen Shot 2021-08-02 at 7 37 10 PM" src="https://user-images.githubusercontent.com/87668369/127940031-a6582907-1a65-43cd-a8fa-1f5d058e5a18.png">

**Comment by Baylink-gh** [comment]
> To my knowledge, the EOL isn't user changeable.

I'd meant to change it on the TA side, and I believe the substance of David's response(s) is that yes you can.

And yes, your EOL is set (what I think is) correctly in that image.

**Comment by JTF4** [comment]
Huh. Everything seems to be in spec for RossTalk. 

Try this:
Run nc -l 7788 and point your TA instance at the computer running net cat. Run the command and see what it outputs to the terminal.

**Comment by JTF4** [comment]
@Appraxa we just released v2.0.5 which contains a native RossTalk action. If you want, you can upgrade and give that a try.

**Comment by Appraxa** [comment]
Yup that seemed to do the trick! Thank you much!

**Comment by JTF4** [comment]
Great!
