### ISSUE TITLE
Stock and Chrome browsers on Alcatel 4.2.2 phone won't work as tally displays

### ISSUE THREAD

**Issue by Baylink-gh** [josephdadams/TallyArbiter#115]
Chrome 31.0.mumble (which has JS V8 3.21.mumble) won't pull up the web tally viewer page; I get an empty page back, no header, no pulldown menu).

This is true for both

http://10.10.10.88
and
http://10.10.10.88/#/tally

though I think the latter is an ersatz URL.  It *does* get the page title, as the tab is named "Tally Arbiter" correctly.

This works fine on Opera Android, for example, on my LG V-20 on the same server install.

Are the minimum requirements for the web tally viewer (what's that actually called? :-) documented?

**Comment by hrueger** [comment]
For the frontend we're using Angular v12. You can find the minimum browser specifications here: https://angular.io/guide/browser-support

Maybe we can add some polyfills to support even older browsers.

**Comment by Baylink-gh** [comment]
Gotcha.

I was trying to run with stock browsers because the 3" screens on these things make so prosaic a task as getting them onto a valid Google account so you can get to the store *insanely* annoying, but it's still easier for me to fix it than for you to do so, unless you've gotten hundreds of this request, and I didn't see them.  :-)

If I upgrade to a current browser and still have problems, I'll reopen this.  Thanks.

As a parting shot: is there a way to get the library to at least leave "Sorry; your browser is too old; please upgrade" in the returned window?
