### ISSUE TITLE
Update Docs Icons

### ISSUE THREAD

**Issue by hrueger** [josephdadams/TallyArbiter#117]
Hey @josephdadams 
I just noticed that you updated the icons. Looks great! We should then also update the two icons / logos of the documentation (https://github.com/josephdadams/TallyArbiter/tree/master/docs/static/img)

**Comment by josephdadams** [comment]
Done!

**Comment by josephdadams** [comment]
I’ll have to resubmit the main logo, I uploaded an all white version which you can’t even see in light mode. 😂

**Comment by josephdadams** [comment]
new color logo added :)
