### ISSUE TITLE
ATEM Mini (Pro, ISO, etc) Cut Bus support (Program-priority tally?)

### ISSUE THREAD

**Issue by roomac** [josephdadams/TallyArbiter#119]
When an ATEM Mini is set to Cut Bus rather than Program/Preview (toggled in the ATEM Setup app), the Mini’s source buttons illuminate red when cutting a source to PGM, but the ATEM Software Control indicates the source is actually being switched to both PGM and PVW. This causes Tally Arbiter clients to turn yellow, rather than the expected PGM red.

Is it possible to have an optional ATEM source setting in TallyArbiter to show red tally when sources are in both PGM and PVW? We don’t want to disable the PVW green tally as it is possible (via the software control, Companion buttons, etc.) to use the PVW bus even when a Mini is set to Cut Bus.

The Cut Bus setting simply governs the behaviour of the hardware buttons to cut the sources to PGM and I think it’s the default operation mode for these switchers out of the box.

**Comment by Baylink-gh** [comment]
I am prone to just manually match them in PVW mode, so I don't accidentally take something I didn't want to, and had already noticed this.  I mentioned it to The Boss in an email a while back, and I think he said that configurable colors were on his roadmap.

**Comment by josephdadams** [comment]
Yes configurable colors for all three bus states (pvw, pgm, pvw+pgm) will come at some point. For now, I would recommend just editing whatever listener client you are using and changing the color used for the pvw+pgm state.

**Comment by Baylink-gh** [comment]
> editing whatever listener client you are using

Pointer for the web client?

**Comment by hrueger** [comment]
You need to change the expression [here](https://github.com/josephdadams/TallyArbiter/blob/111681641950e84010477114cc82d510c3227fd9/UI/src/app/_components/tally/tally.component.html#L15). In particular, you need to change the `bg-warning` which is a [yellow background](https://getbootstrap.com/docs/5.0/utilities/background/#background-color) to `bg-danger` which is red.
Then, you can [run TallyArbiter locally](https://github.com/josephdadams/TallyArbiter#contributing) or build a new installer (`npm run prepare && npm run build-desktop`).

**Comment by Baylink-gh** [comment]
Got it.  And the desktop thing is the new 2.x version that comes out of the installer as an app, and packages up the http server and an HTML control that points to the config pages?  (That's really spiffy, BTW)

**Comment by josephdadams** [comment]
#11

**Comment by JTF4** [comment]
#145

**Comment by JTF4** [comment]
Just finished adding cut bus support. It will be included in version 2.0.10 which should be released on Monday.

**Comment by roomac** [comment]
Amazing, thank you!
