### ISSUE TITLE
M5Stick doesn't show preview/program

### ISSUE THREAD

**Issue by Mitemd** [josephdadams/TallyArbiter#12]
Hey Joseph,

I'm always impressed when people create some new technology stuff. Thanks for your time! I've tried it myself and I got to the point where I see the status of my Camera 1 in the settings as well in the web viewer. I'm a bit proud of myself :D

Code is successfully transferred, I set all up, like you've written here on GitHub and my M5StickC is connected to the network,. Where could be (presumably) my mistake?

Best wishes from Germany :)

**Comment by josephdadams** [comment]
Hey @Mitemd! I of course saw your comment over on YouTube where we have been discussing the issue, where the M5stick is not connected to the Tally Arbiter server because of an incorrect IP address. I'll close this as we will hopefully figure out the issue over there!
