### ISSUE TITLE
TSL Client address error

### ISSUE THREAD

**Issue by videojedi** [josephdadams/TallyArbiter#123]
The data received in an external TSL Client is incorrectly addressed.

According to the TSL protocol, addresses 0-126 are valid only. There is a Hex 80 offset so should be 80 to FE only.

When using wireshark to look at the output of Tally Arbiter I see the following...

addr 0  nothing is sent (missing?)
addr 1 0x81 is sent
addr 126 0xfe is sent
addr 127 0xff sent (illegal addr?)

addr 128 0x00 sent (wrap around illegal address)
addr 129 0x01 sent

**Comment by josephdadams** [comment]
It specifically ignores address 0:
https://github.com/josephdadams/TallyArbiter/blob/111681641950e84010477114cc82d510c3227fd9/index.js#L5642

This is because I am using 0 to assume you don’t want to send TSL data for that particular Device in TA. 

What would you propose to fix the addressing issue? Limit the values that can be entered to 0-126? Is it only a problem for higher than 126?

**Comment by videojedi** [comment]
0 to 126 would follow the specification as published. So I guess it would remove the possibility of problems with third party devices?

[https://tslproducts.com/media/1959/tsl-umd-protocol.pdf](url)

0 is a valid display address, although as we know, Ross starts at 1, as do a couple of other devices I've seen. But TSL Tallyman products and Axon Cerebrum all start at 0 when generating and all read 0 as a valid address.

Is a blank entry assumed to be zero? Could a blank entry be used instead?

**Comment by josephdadams** [comment]
Blanks (or non-number values) currently get evaluated to 0, and then promptly ignored.

I have a commit coming to allow for `0` as an address, with non-numbers evaluating now to `-1` which are then ignored.

I will also update the UI to only allow a valid range.

**Comment by josephdadams** [comment]
Fixed in latest

**Comment by videojedi** [comment]
Great work!

I’ve often wondered why TSL 3 and 4 is limited to 126 displays. Guessing it’s a throw back to the RS422 signal. Header can never be 00 or FF. 

On another subject, have you ever considered passing thru the received  TSL Mnemonic to Tally Arbiter listening devices?

I’ve written a little TSL receiver tool. I use it mainly to help debug large multiview systems. But please feel free to have a look or share if you think it might be useful. 

https://tinyurl.com/tsltester


All the best. 

Many thanks. 


Richard.

**Comment by josephdadams** [comment]
See #104 :) I’m going to have a setting to let the label from the source modify the Device Name property. This will then automatically propagate for TSL Clients, and any Listener Client that supports displaying the Device Name will be updated also.

**Comment by josephdadams** [comment]
@videojedi I've implemented the feature to let the TSL mnemonic modify the device name in #173

**Comment by videojedi** [comment]
Great news. I will update soon. 

Many thanks. 

Richard
