### ISSUE TITLE
Sign in? What is the Account?

### ISSUE THREAD

**Issue by Jinjie-Jack-Wang** [josephdadams/TallyArbiter#124]
<img width="800" alt="图片" src="https://user-images.githubusercontent.com/70709944/127338105-badebda5-c234-4ecf-9ea5-fa323e981d07.png">

**Comment by Baylink-gh** [comment]
The 'traditional' installation instructions give the defaults, 'admin' and 'producer', both with the same password Mel Brooks uses on his luggage.  :-)

**Comment by josephdadams** [comment]
@Jinjie-Jack-Wang you can read the documentation here: https://josephdadams.github.io/TallyArbiter/docs/usage/control-interface

**Comment by Jinjie-Jack-Wang** [comment]
Thank you so much!
