### ISSUE TITLE
Heap Space Problem?

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#125]
Decided to restart from scratch as I was having problems getting the latest version of TA to run. Fresh build on a Raspberry Pi3, latest apt upgrade, node and npm installed. When I attempted to do npm install in tallyarbiter folder, i get this error:
![IMG_20210728_115144](https://user-images.githubusercontent.com/8150022/127364983-0ad017e3-f115-4ce5-9771-2dd8c9f360ea.jpg)

**Comment by wrldtvlr** [comment]
And the detailed log file, if it helps:
[2021-07-28T16_51_25_886Z-debug.log](https://github.com/josephdadams/TallyArbiter/files/6895207/2021-07-28T16_51_25_886Z-debug.log)

**Comment by hrueger** [comment]
When building the frontend, Angular does consume quite a lot of memory. You can try to start the node process with the `--max-old-space-size=1024` to give node 1 GB of memory.
However, you should not need to build TallyArbiter on a Pi. Have you tried our CLI version from npm?

**Comment by wrldtvlr** [comment]
That is easier, isn't it? Now I just have to figure out where the CLI version keeps config.json.

**Comment by wrldtvlr** [comment]
And it's in ~/.local/share/TallyArbiter.

I was confused by the comment on the Build and Run From Source page. It states that to try out latest features, it's necessary to build from source. The CLI install page states to just rerun npm i -g tallyarbiter. Will that pull the latest source?

**Comment by hrueger** [comment]
It will install the latest release. If you want features which are not yet released, you need to build TA from source because we don't ship nightly or beta versions out (yet).

**Comment by josephdadams** [comment]
@hrueger lets set up nightlies 😀

**Comment by hrueger** [comment]
Although I've never done that, it shouldn't be too difficult. I suggest the following:
- Github Action workflow which runs on pushes to the `master` branch (or better add the following steps to the already exisiting build workflow)
- Append `-nightly-[time]` to the `package.json`'s `version` field. `[time]` is the current timestamp.
- build and push the version to npm with the `--tag nightly`

You can then get the latest version with `npm I tallyarbiter@nightly`.

What do you think?

**Comment by josephdadams** [comment]
I like this :)

**Comment by wrldtvlr** [comment]
Thank you for considering this. We run TA in a production environment, but there have been occasions where grabbing the latest build would help troubleshoot an issue.
