### ISSUE TITLE
V2.0.3 problem

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#128]
@hrueger @JTF4 all the commits from yesterday, something might have broken. A user reported on FB that 2.0.2 works perfectly but 2.0.3 doesn’t load at all either in browser or electron window.

**Comment by MatteoGheza** [comment]
I have the same problem. Electron window is empty (white) and opening localhost:4455 returns error 502.

**Comment by MatteoGheza** [comment]
I found the error. I extracted the app.asar file in TallyArbiter resources directory, and I executed `node index.js`.
The error is:
`Error: ENOENT: no such file or directory, open 'C:\Users\ardui\AppData\Roaming\TallyArbiter\logs\Fri Jul 30 2021 16:52:06 GMT+0200 (Ora legale dell’Europa centrale).talog'`
I'm working on a fix.

**Comment by MatteoGheza** [comment]
@josephdadams I developed a quick fix (#129).

**Comment by hrueger** [comment]
Great job! You wrote the comment 2 mins earlier than me ;-)

**Comment by JTF4** [comment]
Ah. Yep! Just ran everything on my windows machine. Didn't catch this issue since I was using a mac.

**Comment by MatteoGheza** [comment]
@hrueger if @josephdadams releases a new version with that fix, will Electron Updater work even if there's an error in index.js?

**Comment by hrueger** [comment]
Hm, I don't know and unfortunately, I don't have time to check.
If it doesnt, we should wrap the `require("index.js")` in a try-catch to prevent issues like this in the future.

**Comment by josephdadams** [comment]
I’m out and about today but if anyone has time to add the try-catch, version bump, and release a new tag, let me know!

**Comment by MatteoGheza** [comment]
@hrueger can you add the try-catch (for ex. #130) and release a new version, since you have write access to the repo?

**Comment by hrueger** [comment]
Yes, I will do that this evening.

**Comment by hrueger** [comment]
fixed with #130

**Comment by hrueger** [comment]
New version (2.0.4) should also be out now. Works for me on Windows.

**Comment by josephdadams** [comment]
Thanks!

**Comment by josephdadams** [comment]
@MatteoGheza you have write access now too. 😃

**Comment by MatteoGheza** [comment]
Thanks!
