### ISSUE TITLE
Mac 2.0.4 Issue 

### ISSUE THREAD

**Issue by hadphild** [josephdadams/TallyArbiter#133]
There was an unexpected error. Please open a bug report on the project's Github page or contact one of the developers. Stack Trace: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received NaN.

**Comment by hrueger** [comment]
Could you please share your config file? Or are you running a fresh clean version?

**Comment by JTF4** [comment]
@hadphild are you still having this problem?

If you are, I would recommend restarting your computer to see if there's a hidden process taking up port 4455.

**Comment by JTF4** [comment]
Closing due to no response.

 If you still experience the issue, please re open and add details.
