### ISSUE TITLE
Error adding OSC source in V2.0.4

### ISSUE THREAD

**Issue by rgw132** [josephdadams/TallyArbiter#137]
Hi,

I'm new to Tally Arbitor and have just installed 2.0.4

Trying to add a OSC source and I keep getting the error "Not all fields filled out!"

It's either a bug or I'm doing something wrong. Here is what I'm doing....
I've logged into the settings page.
Next to "Sources" I click "+Add"
Dialogue box pops up.
Under "--Choose Source Type--" I scroll down and select "Open sound control (OSC)"
Under "Source Name" I call it "Arduino" (Pretty sure this a label for me and doesn't matter)
Under "Port" I enter "8000" (have tried lots of different port numbers)
Click "Ass Source"
I get an "Error" dialog box "Not all fields filled out!"

I've got no other fields to fill out?? What am I doing wrong? Does the Port field need to be in a special format?

I've also tried this from my phone logged into [server laptop IP]:4455 and get the same result.

 
![TA add source](https://user-images.githubusercontent.com/88350450/127928875-87c38de9-9709-4376-98df-14babd44a9bb.png)
![TA Error Msg](https://user-images.githubusercontent.com/88350450/127928880-7d387e89-e67d-4627-abbd-23113085b303.png)

[TA Config.zip](https://github.com/josephdadams/TallyArbiter/files/6919901/TA.Config.zip)

**Comment by JTF4** [comment]
Would you mind uploading for config.json file (located in appdata) so I can mirror your config on my end?

**Comment by rgw132** [comment]
> Would you mind uploading for config.json file (located in appdata) so I can mirror your config on my end?

Yep have done that.

Also forgot to mention that I have successfully added other source types.

**Comment by JTF4** [comment]
Wow. I must be blind. Sorry about that.

**Comment by rgw132** [comment]
> Wow. I must be blind. Sorry about that.

Nope I just added it.

**Comment by JTF4** [comment]
Well.... now that that's behind us. It appears that it's an issue on our end. I'm working on a fix for that now and should have one here soon.

**Comment by rgw132** [comment]
ok perfect, good to know I am smart enough to fill in two fields! :-)

**Comment by JTF4** [comment]
Yep! Just PRed a fix for the issue. If you want to have a look: #138

**Comment by JTF4** [comment]
@rgw132 Version 2.0.5 is live! It contains the bug fix for your OSC problem.
