### ISSUE TITLE
Problem with connection to ATEM 1 M/E

### ISSUE THREAD

**Issue by Dosh22** [josephdadams/TallyArbiter#14]
Hello, I have problem with connection to ATEM 1 M/E switcher... The switcher is green in Web GUI, but in CLI it put these errors:

[Fri Oct 23 2020 15:50:51 GMT+0200 (Central European Summer Time)]     Tally Arbiter running on port 4455
reconnect
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 15. Received 17
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
Failed to deserialize command: Function: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
[Fri Oct 23 2020 15:50:51 GMT+0200 (Central European Summer Time)]     Source: ATEM1 ATEM connection opened.
[Fri Oct 23 2020 15:50:52 GMT+0200 (Central European Summer Time)]     Listener Client Connected. Ty

And I have no tally data from the switcher....

The switcher software is 6.6.1. (Pretty old, but i cann't upgrade it, because of other infrastructure.)

**Comment by josephdadams** [comment]
I am tracking some errors related to the recent ATEM change within Tally Arbiter that was made. At this point if you need ATEM compatibility I recommend using Tally Arbiter 1.3.

**Comment by Dosh22** [comment]
Can you please provide link for version 1.3 to me. Thank you.

**Comment by Dosh22** [comment]
If I try version 1.3 (from github old commits), I get this error, when I try connect ESP32 (m5stick) Listener :(

[2020-10-24T17:11:20.263Z] Caught exception: TypeError: Cannot read property 'id' of undefined
[2020-10-24T17:11:37.404Z] Caught exception: TypeError: Cannot read property 'id' of undefined

**Comment by josephdadams** [comment]
Sure! Happy to see what you’ve created. I am also partnering with @guido-visser and his excellent m5 project for full compatibility with TA. We will have an announcement about that at a later date.

**Comment by josephdadams** [comment]
Try the latest version of Tally Arbiter against your ATEM and see if this is resolved.
