### ISSUE TITLE
Remove unnecessary files from releases

### ISSUE THREAD

**Issue by JTF4** [josephdadams/TallyArbiter#140]
Is there a way that we can automatically remove all of the unnecessary files from the releases? Really all people need are source code dmg Linux and exe files.

**Comment by josephdadams** [comment]
Sure just edit them and remove them

**Comment by hrueger** [comment]
What do you want to remove? The `latest.yml` files? Those are needed for the electron updater to function!

**Comment by hrueger** [comment]
And the `blockmap` file is used for differential updates.

**Comment by JTF4** [comment]
Ahhhhh! Now that I know their purpose, I defiantly don't want to remove them! I've always done manual updating for my projects, so I never actually kept the latest and blockmap files.
