### ISSUE TITLE
Desktop documentation window - can't navigate home again

### ISSUE THREAD

**Issue by CompositeLight** [josephdadams/TallyArbiter#147]
Using V2.0.6 desktop on MacOS, when you start the app a window appears with tabs for Home, Tally View, Producer, Settings. On the Home page, if you follow the documentation link there is no way (that I can find) to navigate back to the Home Screen. Clicking the Tally Arbiter logo in the top corner just refreshes the documentation page. The only way I can find to get back to that original Home Screen is to quit the software and restart.

My suggestion would be that the Documentation Link opens in a new window/pane, as currently happens when you click on a Tally Web Client link from that same home page.

**Comment by MatteoGheza** [comment]
I fixed it about an hour ago in #146

**Comment by MatteoGheza** [comment]
Now I'm going to release a new version

**Comment by CompositeLight** [comment]
Nice one - thanks!

**Comment by MatteoGheza** [comment]
@hrueger there is a problem... Github Actions MacOS isn't working: "socket hang up"
I'm trying to re-run the entire workflow... I don't know...

**Comment by hrueger** [comment]
I've had that (and simular problems) yesterday. It sometimes happens with GitHub actions.

**Comment by MatteoGheza** [comment]
EDIT: now it works

**Comment by MatteoGheza** [comment]
@CompositeLight can you check if the new update works?

**Comment by CompositeLight** [comment]
Just tried 2.0.7. The Documentation Link now does nothing at all (does change colour on mouse over, but nothing opens on click). The Tally Web Clients links now do nothing also.

**Comment by MatteoGheza** [comment]
Oh, it works on my machine... I'm going to rollback the update, while I'm investigating on the problem. I'm sorry...

**Comment by MatteoGheza** [comment]
I forgot to push a commit. Now I'm releasing 2.0.8

**Comment by JTF4** [comment]
@MatteoGheza is 2.0.8 ready to release?

**Comment by MatteoGheza** [comment]
Yes

**Comment by MatteoGheza** [comment]
I released now

**Comment by MatteoGheza** [comment]
@CompositeLight can you try the new update?

**Comment by CompositeLight** [comment]
2.0.8 now works. The only thing I would say is that the new windows, for both the documentation and the Tally Web Clients open at full screen size (very large on my ultra wide monitor!) I think previously the Tally Web Clients opened in a smaller window like the Home one...

**Comment by MatteoGheza** [comment]
Ok, I'll fix It for the next release

**Comment by MatteoGheza** [comment]
Fixed with https://github.com/josephdadams/TallyArbiter/commit/48b8518e3bfa9303f8e97ef0b518fe6544a13a67
It will be released in the next release

**Comment by MatteoGheza** [comment]
> 2.0.8 now works. The only thing I would say is that the new windows, for both the documentation and the Tally Web Clients open at full screen size (very large on my ultra wide monitor!) I think previously the Tally Web Clients opened in a smaller window like the Home one...

Fixed in version 2.0.9
