### ISSUE TITLE
Status of various functions (recording, streaming, etc) 

### ISSUE THREAD

**Issue by fgolman** [josephdadams/TallyArbiter#15]
Would love to see addition of various on/off toggles of various functions as tallys, such as record, stream, etc.

Would be useful in many instances to even act as a trigger for the traditional studio on-air light.

**Comment by josephdadams** [comment]
What tally sources are you referencing that would have this?

**Comment by fgolman** [comment]
I'm suggesting that on the various switchers to be able to observe the status of various noninput conditions, that can be toggle off and on (like recording) and publish it that status. Would work much like a tally but, of course, depends upon each switcher capability and API. The output would be off (green/nothing) or on (red) and would look and work just like a tally as far as downstream devices to your software.

**Comment by josephdadams** [comment]
Let me think about this some. I think the idea has merit, but already seems outside the scope of this project. I’m not opposed, but I also don’t know if I want to implement properties of this nature yet. Companion might be a better tool. I am planning to add an “incoming webhook” tally source which would allow for easy custom triggering like this.

**Comment by Plidian** [comment]
I'd love to see the various tags in the VMIX api be exposed in the Tally UI.  Basically I need to be able to turn on a light when ### `<recording>True</recording>`
But I could see it being useful to capture  the other tags as well
`<external>False</external>
<streaming>False</streaming>
<playList>False</playList>
<multiCorder>False</multiCorder>
<fullscreen>False</fullscreen>`
Sadly the Recording adds an attribute that contains the duration and the file name so I'm not sure if that would make it harder. Fortunately we only care about the value of the tag not any of its attributes.

**Comment by josephdadams** [comment]
@Plidian I can add this if you can get me access to a VMix setup where I can test/develop against it.

**Comment by Plidian** [comment]
I’m happy to help I just would need to know what exactly you need.
The VMIX software has a 90 day free trial, that’s what I’m running on my personal PC.  I’m using that for my learning how to use the software.  The church has a Pro license but the license hasn’t made any difference in the work I’ve done.
If it’s as simple as what the API looks like when the changes happen, I can just copy the XML into an email, but I imagine that wouldn’t help with testing.
Again happy to help just not sure the best way to do so.
-Nathan

**Comment by josephdadams** [comment]
If you’re willing, unattended teamviewer or anydesk access to a computer that is on the same network as the vmix computer so I can interact with the API. I don’t have any Windows machines here to install the vmix trial.

**Comment by josephdadams** [comment]
Added vmix support for this in commit https://github.com/josephdadams/TallyArbiter/commit/1e4bf6b53b47af16d2d5973ee15cde0935d5a55a

**Comment by josephdadams** [comment]
@fgolman does the tricaster have any states like this exposed in their API? I've implemented it now for OBS and VMix. I'll consider adding it for the ATEM Mini Pro's, if that's accessible in their API.

**Comment by josephdadams** [comment]
#204 implements this for ATEM streaming/recording
