### ISSUE TITLE
Improve Bug Template

### ISSUE THREAD

**Issue by hrueger** [josephdadams/TallyArbiter#151]
Hi @JTF4,
I really like your bug template. However, I think for the version an input field would be better as we otherwise have to update the template every time we release a new version. And if we forget that, people might be confused.

And while we're at it, I'd also like to add the following fields:
- Which distribution type of TallyArbiter are you running (select; from source / Desktop / CLI / Docker)
- Which OS?
- (If applicable) what listener clients? (web (and then which browser & OS) / M5 / ...)
What do you think?

**Comment by JTF4** [comment]
I really like that idea! I'll look into dynamically assigning that.

**Comment by JTF4** [comment]
I added all of the fields. It does not look like there is any way to dynamically update the version field at the moment.

Should we just use a text field for it? Or just add appending the version to our update procedure?

@josephdadams do you have an opinion on how to do the version field?

**Comment by josephdadams** [comment]
Text field is fine. We will always encourage people to try the latest version before considering their issue valid anyways.

**Comment by MatteoGheza** [comment]
Now "version" is just a text field

**Comment by JTF4** [comment]
Sweet! If since everything here is done im gonna go ahead and close the issue
