### ISSUE TITLE
Actions not running on new version tag

### ISSUE THREAD

**Issue by JTF4** [josephdadams/TallyArbiter#159]
When I make a new version, our actions are not running. I thought that may have been me tagging a new release at the same time Joesph merged a PR, but after making another tag, it still will not run the action and build.

@hrueger

**Comment by hrueger** [comment]
Did you push the tag using `git push --tags`? I can't see them in the GitHub tag list...

**Comment by JTF4** [comment]
Yep. After leaving them up for about 5 mins and nothing happening, I deleted them to try pushing the tag, but after repeating again, nothing happened.

**Comment by JTF4** [comment]
I just tried to run the workflow manually and nothing happened. Could @josephdadams be out of free action time?

**Comment by josephdadams** [comment]
Did you create the tag with `git tag v2.0.10` before the push?

**Comment by hrueger** [comment]
It has always been working for me. At least the Tag should appear in the tag list, even if the Action does not run. Maybe something us wrong at your end? Are you pushing tags to a fork?

For public repositories the Action usage is unlimited.

**Comment by JTF4** [comment]
I'm pushing tags to master, and creating the tag before pushing it. 

I'll try again in an hour.

**Comment by hrueger** [comment]
What do you mean with pushing tags to master? As far as I know, tags are not tied to a specific branch.

Just to make sure that we're all talking about the same: you're updating the version field in the `package.json` file, then committing that, pushing that commit, then running `git tag v2.0.10` and then pushing this tag to GitHub?

**Comment by hrueger** [comment]
GitHub Actions may actually have a problem right now: https://www.githubstatus.com/ but I'm still wondering why the tag doesn't even show up.

**Comment by JTF4** [comment]
Ahhhhhhh. You could not see the tag because I deleted it. You can see it now, but the action is not running because of the downed service. I'm working on a build server for us to use anyway. That way in the future we don't have to worry about this.

**Comment by MatteoGheza** [comment]
Do you mean using https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners ?

**Comment by JTF4** [comment]
yep!

**Comment by JTF4** [comment]
Ahhhhhhhhhh!
