### ISSUE TITLE
Webhook preview / pgm duplicate off message on webhook

### ISSUE THREAD

**Issue by Boguinhos** [josephdadams/TallyArbiter#16]
Hello everyone!
Is it just me that have the idea that when i have a source on preview and press cut, the green tally goes red as it is supposed. but if i cut back again, that signal should be green again but it goes black.
I'm using webhook. 
Since the OFF order on my webhook device is always unit, i see it blinking green for some fast instants and then goes black. What it seems to be happening is having the hook for green but since PRGRAM is off, the last hook that goes is the PGM /OFF instead of the PRV ON.

Can someone confirm this? thank you

**Comment by josephdadams** [comment]
This is, more or less, the reason I developed listener clients, so the logic could be included to handle conditions like this.

At some point, Tally Arbiter will get options like "In PGM and NOT PVW", etc.

**Comment by josephdadams** [comment]
Would an adjustable delay field (in milliseconds) per device action help with this?
