### ISSUE TITLE
Suggest bug report when process has unhandled exception

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#162]
### What feature would you like to see added to TallyArbiter?

```javascript
process.on('uncaughtException', function (err) {
      //the cool stuff here
});
```

Use the uncaught exception function to send a socketio alert to the UI, suggesting they submit a bug report. We could either store the uncaught exceptions in an array and periodically send a socketio to the UI, in case the error happened when no one had the UI open. It would just be a nice way to catch errors we don't know about or help the user report bugs to us.

Would be helpful for users not running the electron version, which already has something like this.

**Comment by MatteoGheza** [comment]
I'm working on it.

**Comment by MatteoGheza** [comment]
Done in #157
