### ISSUE TITLE
Listener will not connect when there is no internet connection

### ISSUE THREAD

**Issue by peterfdej** [josephdadams/TallyArbiter#168]
### What happened?

We have a mobile set (portable case) with an Atem, router (with WiFi) and switch for recording and broadcasting (streaming) on locations. TallyArbiter runs on a Raspberry Pi4 in the same network. We use TTGO-display (like the M5) devices as listeners.
When the router is not connect to the internet (no connection on the WLAN port of the router) the listeners will not connect to de TallyArbiter server. As soon as I plug in a cable in the WLAN port to get internet connection, the listeners are connecting to the TallyArbiter server. The webportal is working well in both situations. 

### Version

version of this week

### Distribution

CLI

### OS

Linux

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by josephdadams** [comment]
I can try to recreate this in a sandbox. It will have to be with m5 or blink1 as I don’t have any ttgo’s. If I do and it works, then basically my assumption would be it’s related to your router or network setup in some fashion. Do you have another network setup you could test with? As far as I know, we don’t have any external dependencies which would require internet access.

**Comment by peterfdej** [comment]
I will try it in a different network. Will let you know.
