### ISSUE TITLE
Flashing a Cloud Listener Client throws an error

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#169]
### What happened?

If you try to flash a listener client that's a cloud connection, it is not happy.

### Version

2.0.9

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Firefox

**Comment by josephdadams** [comment]
@MatteoGheza can #192 help with this also?

**Comment by MatteoGheza** [comment]
Do you remember the stacktrace of the error?
I can't reproduce this now.
