### ISSUE TITLE
Latest version receives incorrect data from ATEM

### ISSUE THREAD

**Issue by DanableLecter** [josephdadams/TallyArbiter#17]
Hi, I tried out your software a month or so ago in the previous build to capture data from an ATEM broadcast studio and convert to an OSC command to trigger timeline points in the server which worked great.

I've just installed the latest build on a machine and on comparing the data coming in to the old build vs the new build, new build sees input 1 as PVW: True / PGM: True regardless of which input is selected in the pgm/pvw on the ATEM switcher. I have both builds running on two machines on the same network connected to the same ATEM and the old version works as expected.

The old version can get laggy with fast button pushes - I presume its reading the tally data from all M/E which slows it down hence the update to select m/e in the latest build but something seem broken.

Thanks

**Comment by josephdadams** [comment]
There is definitely some error checking/handling that needs to be done with the ATEM part of Tally Arbiter. I changed connection libraries completely as the "old" one only supported 1 ME, however it is not correctly handling multiple MEs and I only have 1 ME to test on here. Once I line up some time to test on someone else's ATEM with multiple MEs, I will see if I can get it fixed.

**Comment by DanableLecter** [comment]
Ok great - good to know thanks - it had me stumped for a while!

**Comment by skermanator** [comment]
I have the same issue. It allways pulls from me2 and input 1 on me1. 

Is there a way for me to install the old version. just need the data from ME1

**Comment by josephdadams** [comment]
Sorry about that. Here is a link to 1.3 based on the Github commits: https://github.com/josephdadams/TallyArbiter/tree/94afe58e57f0e10aa464510b034bcf29724f10a0

**Comment by skermanator** [comment]
> Sorry about that. Here is a link to 1.3 based on the Github commits: https://github.com/josephdadams/TallyArbiter/tree/94afe58e57f0e10aa464510b034bcf29724f10a0

Thanks for the fast response.  awesome program to sit next to companion

**Comment by sledzik1984** [comment]
Same here. I have Atem 2 M/E but Tally Arbiter always take data from ME/2

**Comment by josephdadams** [comment]
Try it now, it should be working as expected.
