### ISSUE TITLE
MDNS support

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#174]
### What feature would you like to see added to TallyArbiter?

We should have the server broadcast itself to help clients more easily connect. We should also implement an mdns browser client so the server can search for things like ATEM etc on the network.

**Comment by JTF4** [comment]
Should be simple enough. I'll work on this with a new M5 client over the next week or so.

**Comment by josephdadams** [comment]
Midi relay does it if you want something to copy 😃

**Comment by MatteoGheza** [comment]
I'll leave this open until #228 is closed.
