### ISSUE TITLE
Workaround: Autostart for Win10

### ISSUE THREAD

**Issue by DachsbauTV** [josephdadams/TallyArbiter#18]
I found a workaround for autostarting the TallyArbiter on Win10 which I wanted to share with you and everyone who might need it:

1. Install Node and pm2 as explained in the readme
2. Setup a "nouac" rule to autostart with admin priviliges in task scheduler: https://youtu.be/QMh5MAV-m6E?t=167
3. Create a batch file to start TA as a service:
`cd C:\Program Files\TallyArbiter-master
pm2 start index.js --name TallyArbiter
PAUSE`

4. Create a second batch file for the auto start process:

`copy /-Y /V start-tally.bat %temp%\cmd.cmd /Y
echo %~dp0 > %temp%\startin.txt
schtasks /run /tn nouac`

5. Create a shortcut of the autostart batch file in shell:startup 

Hope this helps.

**Comment by josephdadams** [comment]
This is great!

**Comment by DachsbauTV** [comment]
Also works for the Midi relay of course :) Setting that up as we speak. Thanks for all the great tools you'Ve been creating

**Comment by guido-visser** [comment]
I would personally fix this by using [NSSM](nssm.cc). That way TA is a service that's being booted every time upon login :)

**Comment by DachsbauTV** [comment]
What a great app! Thanks for bringing that up. It solves other problems I've been trying to solve :)

However, can it start applications as admin privileges? Couldn't find that in the doc?

**Comment by guido-visser** [comment]
@DachsbauTV There is a logon function:
[Imgur](https://imgur.com/DXYeSTE)

It looks like that is what you're looking for right?

**Comment by josephdadams** [comment]
@DachsbauTV can you add this documentation to the wiki?

**Comment by HowardGolton** [comment]
I found it much easier to just use the pm2-windows-startup utility available here: [https://github.com/marklagendijk/node-pm2-windows-startup](url)

**Comment by DachsbauTV** [comment]
@josephdadams sorry i was really busy with a big production...

However, I've just tried @HowardGolton s pm2 startup (https://www.npmjs.com/package/pm2-windows-startup) and it works flawlessly!. So it is even better than my workaround tool!

**Comment by josephdadams** [comment]
@DachsbauTV that's great! Will you make sure the [wiki](https://github.com/josephdadams/TallyArbiter/wiki/Getting-Started:-Running) is accurate? :) :)
