### ISSUE TITLE
[Feature Request]: OBS source mutes as tally status

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#180]
### What feature would you like to see added to TallyArbiter?

Someone on youtube wants to be able to light up a tally light whenever a mic is unmuted or muted in OBS.

**Comment by MatteoGheza** [comment]
I'm working on it.

**Comment by MatteoGheza** [comment]
> ### What feature would you like to see added to TallyArbiter?
> Someone on youtube wants to be able to light up a tally light whenever a mic is unmuted or muted in OBS.

Done.
