### ISSUE TITLE
Blackmagic ATEM - Show PVW/PGM status when source is used in Upstream Key

### ISSUE THREAD

**Issue by aacoba** [josephdadams/TallyArbiter#20]
ATEM supports using an input as an "picture in picture" overlay using the UpstreamKey (USK) DVE functionalities.
Currently TallyArbiter does not recognize an input as being "used" in the USK and does not update the tallies accordingly.
It looks like the PGM state of the USK can be found in https://nrkno.github.io/tv-automation-atem-connection/interfaces/upstreamkeyer.html by looking at `onAir` and `fillSource`.

The PVW state looks to be a bit more difficult to determine. When I include the key in the next transition (include it in the PVW) I see that the `video.ME.0.transitionProperties` state gets updated.
The content of the state is `{ style: 0, selection: 3, nextStyle: 0, nextSelection: 3 }` where both selection and nextSelection change with the keys included in the next transition. 
It looks like the value of `selection` and `nextSelection` can be translated back into the binary version of which keys are included in the transition.
![image](https://user-images.githubusercontent.com/659308/100484884-6dfc2680-30fe-11eb-8db6-55f1b39609b0.png)
For example:
Only BKGD -> 1
BKGD + KEY1 -> 3
KEY1 -> 2

It would be very useful for us if TallyArbiter is able to represent this correctly in the future!

**Comment by josephdadams** [comment]
@aacoba I will see if I can get this added at some point!

**Comment by wicherdt** [comment]
Yes, it is very important in green screen virtual productions.
Please make it.

**Comment by ruebyi** [comment]
Would be great to see this in a future Update - the new ATEM Extreme has 4 Upstream Keyers, so it would be very helpful to get feedback about their Status.

**Comment by josephdadams** [comment]
This should be fixed in latest
