### ISSUE TITLE
[Feature Request]: Print error Stack Trace to the console

### ISSUE THREAD

**Issue by hrueger** [josephdadams/TallyArbiter#201]
### What feature would you like to see added to TallyArbiter?

Currently error stack traces are just visible in the error log. In the terminal I just see 
```
Caught exception: TypeError: Cannot read property 'includes' of undefined
```
For development and debugging it would be could if we logged the full error stack trace to the console (for example using `console.trace(error);`

**Comment by MatteoGheza** [comment]
Done in https://github.com/josephdadams/TallyArbiter/commit/f56ff99ffdd2129801d2d98feb8f6ad492cac344
