### ISSUE TITLE
NPM Releases?

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#203]
I tried to do an NPM CLI update the other day, but the release stayed at 2.0.9. I gather it will follow behind github main releases?

**Comment by hrueger** [comment]
If you go to https://www.npmjs.com/package/tallyarbiter and click on the _Versions_ tav, you can see all releases until the latest one, 2.0.14. 

How did you try to update? 

I always use https://www.npmjs.com/package/npm-check-updates for that.

**Comment by wrldtvlr** [comment]
I just followed the upgrade instructions and used sudo npm i -g tallyarbiter. I'll look at it again today.
