### ISSUE TITLE
[Documentation]: Add info on how to backup the config file

### ISSUE THREAD

**Issue by kenm-4682** [josephdadams/TallyArbiter#206]
Some pages of the TA Documentation ([here for CLI](https://josephdadams.github.io/TallyArbiter/docs/installation/cli), [here for desktop](https://josephdadams.github.io/TallyArbiter/docs/installation/desktop-app#configuration)) mention the need to "backup the config file" before updating or to save configs so they don't get lost.

Those statements on the pages hyperlink to #configuration anchors, which are non-existent -- so I can't find instruction on how to do that.

Could some easy documentation be written on how to backup the config file for both CLI (I'm on a Raspberry Pi/CompanionPi) and other OS's? 

Or, more advanced, perhaps this turns into a feature request with an "export config" button so that it pops out the config file with a place to save it.

**Comment by hrueger** [comment]
Hi @kenm-4682,
the export feature is tracked in #164 , however, updating the docs sounds like a good idea 👍
