### ISSUE TITLE
[Bug]: No icon in the dialog when quitting from the Menubar (Mac OS)

### ISSUE THREAD

**Issue by mg-1999** [josephdadams/TallyArbiter#209]
### What happened?

When using the quit function from the menubar nog icon is show in the dialog window.

### Version

2.0.14

### Distribution

Desktop

### OS

MacOS

**Comment by JTF4** [comment]
@mg-1999 can you be a little more specific on the issue you're experiencing?

**Comment by mg-1999** [comment]
On the first run of the programme. The icon was missing in this dialog window. But somehow it's there now... 

Also reproducing hasn't succeeded yet. The bug is gone on a fresh install.

<img width="420" alt="Dialog TA" src="https://user-images.githubusercontent.com/6923382/132348596-e8795fbc-7738-48f6-a71c-1159d304ae2f.png">

**Comment by josephdadams** [comment]
Feel free to close if you think it is resolved.
