### ISSUE TITLE
Add Videohub

### ISSUE THREAD

**Issue by Keksstar** [josephdadams/TallyArbiter#21]
Hi Joseph,

could you please add the BMD Videohub protocol?

Example for this: You have an preview monitor for the video engineer who´s doing iris etc on the cameras. He selects his cameras via an Videohub. Would be great if he can get an tally information if the camera which he has in preview is on air or not.
So needs some logic if camera is on air and on output xyz of the videohub.

Thanks in advance,
Andreas

**Comment by josephdadams** [comment]
Would it be sufficient, if, when adding the VideoHub as a tally source, that you picked each output that you wanted to monitor and specified whether it should be a preview or program (or both) tally?

**Comment by Keksstar** [comment]
So as an example you add output 12 of the Videohub as an source to monitor. This output can than be feed to an TSL UMD, etc. - correct?
But then it needs the "logic": If camera 3 has tally from any source (Mixer or sth.) and is routed to output 12 the TSL UMD needs to light up. If camera 2, which has no tally, is routed to output 12 the TSL should not light up.

I think you´ve got what I mean :D

**Comment by josephdadams** [comment]
The way that Tally Arbiter is currently designed is that you monitor tally status by device (an input) not by a destination (a bus/output).

However, I think you could accomplish what you want by doing one of two things:

- A dedicated tally client for each camera (using any of the supported TA clients)
- A "rolling" tally client that, when you press a button to route that camera source to the shader monitor, also reassigns the TA tally client to the currently selected camera source. Your button panel that you use to change videohub routes to the shader monitor would also need to be capable of sending the API request to the TA server to negotiate this reassignment. You could do this with Bitfocus Companion and a streamdeck. I would have to add this capability to the Companion module (to reassign TA clients).

I can still look at adding the VideoHub protocol as an incoming tally source as I described earlier.

**Comment by Keksstar** [comment]
Would be great if you can have a look on the videohub protocol as incoming source. I guess you already have an idea there.
I guess the status update of the Videohub can be used as it spits out the route if I remember correctly...

**Comment by josephdadams** [comment]
I've added VideoHub support in 1.4.4. It's available now.

**Comment by Keksstar** [comment]
Hi Joseph, thanks for that. Checked it out and it´s working perfect.

Do you have an idea on how to solve this "rolling tally client" that you described? I don´t know on which position the "intelligent" part needs to be added. "When camera 5 has Tally AND is routed to output X of Videohub, then output the Tally for this Videohub output"

**Comment by josephdadams** [comment]
I was suggesting having a Companion button that when you press it, it does the videohub route needed to bring that camera up on your shader, and also reassigns a tally arbiter client to that same camera.
