### ISSUE TITLE
[Bug]: Listener Timeout

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#215]
### What happened?

I'm not sure this is a bug, but we're struggling to understand how the new listener timeout logic is supposed to work. On a typical Sunday, I'll bring up the ATEM in the production room. TA Server and the clients tend to stay up all the time, Power cycling the server is not difficult. The clients are mounted quite high with remote cameras.

Until the listener auto reconnect logic is implemented, I need to reboot the M5 Matrix listeners and relink them to the correct source. All a bit manual, but manageable as previous version of TA Server worked fine through early rehearsal and several services.

What we are seeing with 2.0.14 are multiple listener timeout disconnects. Is it possible that these are occurring because a specific listener is not being assigned to Preview or Program for a long interval? This is a common situation for us, especially during the preservice rehearsal.

Suggestions for making things a bit more resilient?

### Version

2.0.0.14

### Distribution

CLI

### OS

Linux

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by JTF4** [comment]
And this was never an issue until 2.0.14?

**Comment by wrldtvlr** [comment]
No... Things were reasonably stable, at least through Sunday. Some, but not all the listeners just disappear from the Settings page.

**Comment by josephdadams** [comment]
Unless you are running PR #204 there is not any new listener timeout logic. So if you are seeing disconnects, it is your clients dropping their wifi. Otherwise the socket.io library is supposed to keep them alive and connected. It is independent of the individual tally states. Which M5 matrix client are you using? The official TA one?

**Comment by josephdadams** [comment]
Also do they reconnect to the TA server or do they stay disconnected?

**Comment by wrldtvlr** [comment]
Yes, we are using Matrix client from TA. Only mod is to add static addresses. Entirely possible problem is on our end. I'll investigate further.

**Comment by wrldtvlr** [comment]
Ok, this is a first. We have lots of Matrix modules, but this is the first time we've had one fail. Loaded a spare and it worked fine with 2.0.9 and 2.0.14.

Strange failure mode - just seems to affect the WiFi function.

**Comment by josephdadams** [comment]
@JTF4 maybe the same problem we are having with ours?

**Comment by JTF4** [comment]
Possibly. What kind of access point are you using @wrldtvlr?

**Comment by wrldtvlr** [comment]
Rukus650. I'll try the Matrix at home with an Asus router when I have a chance.
