### ISSUE TITLE
On Air Indicator 

### ISSUE THREAD

**Issue by Moving-Light** [josephdadams/TallyArbiter#22]
Hey Joseph!

Is there any way that an indicator on the tally page could be added to show when our system is on air.  If there is any way this could be integrated with our tricaster's live stream that would be great but doing it manually from the producer page could also work.

Thank you so much!

**Comment by josephdadams** [comment]
@Moving-Light do you stream directly from the Tricaster? Do you know if this data is available in their API?

**Comment by Moving-Light** [comment]
We do stream directly from our tricaster to vimeo.  I don't know if it is in the api.  I can check tomorrow once I have lan access to the tricaster.

**Comment by Moving-Light** [comment]
@josephdadams I checked the docs and it is not possible.  Saying that could a checkbox or toggle be added to the producer page be added to display an icon on the tally pages to show if live?

**Comment by josephdadams** [comment]
@Moving-Light I have on the planned features list to add a messaging feature with pre-defined options to allow the Producer page to send messages to all the tally clients viewing on the web page. I think we could accomplish what you want with that feature.

**Comment by TotalInsanity4** [comment]
The feature as described in the initial comment would still be excellent for OBS Studio, Vmix, Ross products, etc. to show on-air and recording information where supported. I don't know of any GPIO software that does both tally and on-air for OBS Studio, for instance, and they're both very useful pieces of information to have visible.

OBS Studio has "streaming" and "recording" as websocket booleans, Ross' older switchers give on-air information via GPO, I'm sure Vmix has some way of reporting live status as well

**Comment by josephdadams** [comment]
I am going to close this since we support both streaming and recording status from several source types.
