### ISSUE TITLE
[Feature Request]: Sound on State Change

### ISSUE THREAD

**Issue by crazytechkid** [josephdadams/TallyArbiter#221]
### What feature would you like to see added to TallyArbiter?

I was wondering if you were planning on adding a sound to play when the state changes. Like when a camera goes to preview the webpage will say like preview or make a noise. I would like this because I cant really mount my phone to my camera but if I could put in a pair of headphones and hear when my tally goes, it could make my life a lot easier. I feel like this is an easy feature to add with not a lot of code involved. If you wont add it is there a way that I can add it myself? Maybe add a setting so that you can toggle in on and off?

**Comment by JTF4** [comment]
It's definitely possible. I'll add it to a list of things to consider for version three￼. There will be a little more code involved than you think though because we have to create a audio transfer and handler function in the web UI. ￼
￼￼

**Comment by josephdadams** [comment]
@crazytechkid If you want to fork the project and add this feature, I think it’s a great idea! You’re personally motivated to make it work, and it will be a great way to learn! 😃

**Comment by josephdadams** [comment]
@JTF4 Orator, one day 😃

**Comment by JTF4** [comment]
Very true!

**Comment by josephdadams** [comment]
@crazytechkid did you ever get it working? I noticed you forked and tried.

**Comment by crazytechkid** [comment]
im working on it. chrome really doesnt like autoplaying audio through a browser

**Comment by josephdadams** [comment]
Yeah. Look into the `Howler` js library: https://github.com/goldfire/howler.js

**Comment by josephdadams** [comment]
put them in `/UI/src/assets/` and then in your HTML you can reference them as `assets/audio.mp3`.

**Comment by josephdadams** [comment]
Feel free to submit a PR to the main repo when you get it polished up. A toggle switch to either play sounds or not play sounds would be nice.

**Comment by crazytechkid** [comment]
i see. I will get to it when I get to it, but right now since I will always have the audio on its not top priority for me
