### ISSUE TITLE
[discussion] Preparing for Hacktoberfest

### ISSUE THREAD

**Issue by MatteoGheza** [josephdadams/TallyArbiter#222]
I think we can prepare this repo for Hacktobest2021, because it can attract new contributors helping us fixing issues and implementing features.

[Official Hacktoberfest 2021 website](https://hacktoberfest.digitalocean.com/)

Doing this, we can continue to contribute as usual (according to school/work), besides, if you open at least 4 PR that receives the "hacktoberfest-accepted" label, you can get one limited edition t-shirt.

The only requirement for partecipating with PR to this repo is adding the "hacktoberfest" topic to this repo (according to the official FAQ).

I think that we can merge #204 and then we can start working on "Incoming Webhook" and "Internal Test Mode", or we can add a new issue with the "hacktoberfest" label so someone partecipating can implement this feature for us and open a PR.

**Comment by josephdadams** [comment]
I think participating is a great idea. I’m not sure merging #204 is a good idea yet because we have a lot of todos and tests for the various source types that still need doing. But if we can capture all that info and put it somewhere, then I’m open to the merge. Or whatever you think is best. It would be great to see more contributors. 😃

**Comment by hrueger** [comment]
What if we merge #204 and release this as a beta version? This way, users who want to try the new features can do that, but the autoupdater wont download the release itself. 
We may need to update the action to support beta versions, I don't quite know.

**Comment by MatteoGheza** [comment]
I think that releasing a beta version with #204 is a good idea.
Electron Autoupdater should skip releases marked with "pre-release", so we don't need to update the Action for this, but I haven't tryied yet.

**Comment by MatteoGheza** [comment]
@josephdadams can you add "hacktoberfest" topic to this repository?

https://user-images.githubusercontent.com/27729549/136047704-dd0d0f49-13ec-4191-95c3-9f2711740064.mp4

**Comment by josephdadams** [comment]
@MatteoGheza done

**Comment by MatteoGheza** [comment]
@josephdadams I'm sorry to bother you on Saturday.
Can you add the topic again for the 2022 edition?
I have a few PR to submit and it would be great to have these counted as Hacktoberfest contributions, but if you don't want to do so in these days I'll submit PR anyway.

**Comment by josephdadams** [comment]
added `hacktoberfest` topic

@JTF4
