### ISSUE TITLE
[Feature Request]: Detect ATEMs in network using Bonjour

### ISSUE THREAD

**Issue by MatteoGheza** [josephdadams/TallyArbiter#228]
### What feature would you like to see added to TallyArbiter?

I think that we can use Bonjour (already installed for advertising TallyArbiter to the network) to detect Blackmagic Atem:
Example:
```js
bonjour.find({
  "type": "blackmagic"
  "txt": {
    "class": "AtemSwitcher"
  }
}, callback);
```

**Comment by josephdadams** [comment]
Can we close this? @MatteoGheza
