### ISSUE TITLE
Problem updating tally with non-standard inputs (INPUT#) on Tricaster

### ISSUE THREAD

**Issue by Moving-Light** [josephdadams/TallyArbiter#24]
Hey @josephdadams!

I was testing out TallyArbiter on my TC1 and I found a bug where the tally does not update when I have any source that does not begin with "INPUT" in preview or tally.  The tally just freezes and does not update until I put a normal input in program or preview (sometimes it has to be in program or it won't update) I know that sources like DDR1 are in the tally API.  I can send the API XML with the source list to you if you need it.  Thanks!

**Comment by josephdadams** [comment]
I probably need that XML list. Do you get any error messages in the console when you put DDR1 in pvw or pgm?

**Comment by josephdadams** [comment]
(I don't have access to or use a Tricaster so I'll have to rely on you and others for testing.)

**Comment by Moving-Light** [comment]
All fine.  I have access to it every weekday.  I am attaching the XML to this comment.  Let me know if you want me to run anything tomorrow as I will be away from the unit until tomorrow.  There are no error messages and only the inputs (INPUT1 - INPUT8) come up even though others are not in the tally console.  I don't need to have working ddr tallies but the normal input tallies not works is an issue.

Tricaster TC1 Tally API:
[dictionary.txt](https://github.com/josephdadams/TallyArbiter/files/5618230/dictionary.txt)

**Comment by fgolman** [comment]
Are you 100% sure this is the case? I've got Input 1, 2 and 3 renamed to REM 1, 2 and 3 (and on-screen with person's name).

Seems to be working fine.

**Comment by Moving-Light** [comment]
@fgolman the issue comes up when using DDRs.  For some reason, the tally watcher does not identify them for my TC1 so it appears like an input is in the program when it really is not.  The Tricaster API does not output any of the renames so it still says "input1" and "input5" though input 5 is renamed spark1 in software.  Can you test it to see if the tally changes when changing between an input and ddr on your 8000 as it could be a TC1 thing.

**Comment by fgolman** [comment]
Just tested with 1.4.3 and switching to/from an input with different name and DDR1 works fine. Tally tracks exactly. HOWEVER, I did note that the Producer Screen isn't working at all, for any input. The tallys track on the settings and tally view screens, though.

**Comment by Moving-Light** [comment]
Hmm.  It might be a TC1 thing then.  Do you mind letting me see your tally API result?  It is **http://_IP_/v1/dictionary?key=tally**.  It might be because of how the apis are different between the two units.  I am also on AE2.

**Comment by fgolman** [comment]
I'm on AE3 and looking at this it appears that the names I've assigned to inputs 1-4 just stay in the UI and don't propagate to the lower levels of the XML schema:

<tally>
<column name="input1" index="0" on_pgm="true" on_prev="false" ndi_id="0"/>
<column name="input2" index="1" on_pgm="false" on_prev="true" ndi_id="1"/>
<column name="input3" index="2" on_pgm="false" on_prev="false" ndi_id="2"/>
<column name="input4" index="3" on_pgm="false" on_prev="false" ndi_id="3"/>
<column name="input5" index="4" on_pgm="false" on_prev="false" ndi_id="4"/>
<column name="input6" index="5" on_pgm="false" on_prev="false" ndi_id="5"/>
<column name="input7" index="6" on_pgm="false" on_prev="false" ndi_id="6"/>
<column name="input8" index="7" on_pgm="false" on_prev="false" ndi_id="7"/>
<column name="input9" index="8" on_pgm="false" on_prev="false" ndi_id="8"/>
<column name="input10" index="9" on_pgm="false" on_prev="false" ndi_id="9"/>
<column name="input11" index="10" on_pgm="false" on_prev="false" ndi_id="10"/>
<column name="input12" index="11" on_pgm="false" on_prev="false" ndi_id="11"/>
<column name="bfr1" index="12" on_pgm="false" on_prev="false"/>
<column name="bfr2" index="13" on_pgm="false" on_prev="false"/>
<column name="bfr3" index="14" on_pgm="false" on_prev="false"/>
<column name="sound" index="-2" on_pgm="false" on_prev="false"/>
<column name="bfr4" index="15" on_pgm="false" on_prev="false"/>
<column name="black" index="-1" on_pgm="false" on_prev="false"/>
<column name="bfr5" index="16" on_pgm="false" on_prev="false"/>
<column name="bfr6" index="17" on_pgm="true" on_prev="false"/>
<column name="bfr7" index="18" on_pgm="false" on_prev="false"/>
<column name="bfr8" index="19" on_pgm="false" on_prev="false"/>
<column name="bfr9" index="20" on_pgm="false" on_prev="false"/>
<column name="bfr10" index="21" on_pgm="false" on_prev="false"/>
<column name="bfr11" index="22" on_pgm="false" on_prev="false"/>
<column name="bfr12" index="23" on_pgm="false" on_prev="false"/>
<column name="bfr13" index="24" on_pgm="false" on_prev="false"/>
<column name="bfr14" index="25" on_pgm="false" on_prev="false"/>
<column name="bfr15" index="26" on_pgm="false" on_prev="false"/>
<column name="ddr1_a" index="27" on_pgm="false" on_prev="false"/>
<column name="ddr1_b" index="28" on_pgm="false" on_prev="false"/>
<column name="ddr2_a" index="29" on_pgm="false" on_prev="false"/>
<column name="ddr2_b" index="30" on_pgm="false" on_prev="false"/>
<column name="gfx1_a" index="31" on_pgm="false" on_prev="false"/>
<column name="gfx1_b" index="32" on_pgm="false" on_prev="false"/>
<column name="gfx2_a" index="33" on_pgm="false" on_prev="false"/>
<column name="gfx2_b" index="34" on_pgm="false" on_prev="false"/>
<column name="ddr1" index="35" on_pgm="false" on_prev="false"/>
<column name="ddr2" index="36" on_pgm="false" on_prev="false"/>
<column name="gfx1" index="37" on_pgm="false" on_prev="false"/>
<column name="gfx2" index="38" on_pgm="false" on_prev="false"/>
<column name="v1" index="39" on_pgm="false" on_prev="false"/>
<column name="v2" index="40" on_pgm="false" on_prev="false"/>
<column name="v3" index="41" on_pgm="false" on_prev="false"/>
<column name="v4" index="42" on_pgm="false" on_prev="false"/>
<column name="v5" index="43" on_pgm="false" on_prev="false"/>
<column name="v6" index="44" on_pgm="false" on_prev="false"/>
<column name="v7" index="45" on_pgm="false" on_prev="false"/>
<column name="v8" index="46" on_pgm="false" on_prev="false"/>
<column name="preview" index="47" on_pgm="false" on_prev="false"/>
<column name="me_preview" index="48" on_pgm="false" on_prev="false"/>
<column name="me_follow" index="49" on_pgm="false" on_prev="false"/>
<column name="previz" index="50" on_pgm="false" on_prev="false"/>
<column name="web_follow" index="51" on_pgm="false" on_prev="false"/>
</tally>


________________________________

**Comment by Moving-Light** [comment]
It could be with different software versions but that shouldn't make a difference seeing that the two look similar.   I am going to take another look at everything tomorrow and running the tally script on a computer over lan instead of wifi as some of the data could of been lost.   @josephdadams let me know if you want any more api info from me.

**Comment by josephdadams** [comment]
The XML that I process is `<shortcut_states>`. It does not look like the data you guys are sharing.

I initiate a TCP connection to the switcher and use this command: `<register name="NTK_states"/>`

```xml
<shortcut_states>
 <shortcut_state name="program_tally" value="INPUT1|BFR2|DDR3" type="" sender="" />
 <shortcut_state name="preview_tally" value="INPUT7" type="" sender="" />
</shortcut_states>
```
I then do a split on the `|` (pipe) character and uses the resulting array.

The TCP socket returns data automatically rather than using the HTTP request where I would have to poll the device on an interval for data.

**Comment by Moving-Light** [comment]
Oh.  I was going off the documentation from newtek and how they said to get tally.  I will be booting our machine up in around 2 hours for a show if you want me to grab the shortcut states api from our machine.   I also updated to 1.4.3 last night so that might change something.

**Comment by josephdadams** [comment]
So did we land on this being a Newtek API problem?

**Comment by josephdadams** [comment]
Did you guys ever make any progress on this?

**Comment by Moving-Light** [comment]
We never did.  I have tested it again recently and the problem is still there.  Even on the most recent version of AE3.  Wonder if there is a way to manually check the tally dictionary when TallyArbiter does not see anything in program or preview.  That could solve the issue.

**Comment by josephdadams** [comment]
Is that data returned in their TCP api?

**Comment by Moving-Light** [comment]
It is the http://_IP_/v1/dictionary?key=tally call.  If your able to check if nothing is in the preview and/or program, you could pull the tally status from here.  This is how the response comes out:
[dictionary.txt](https://github.com/josephdadams/TallyArbiter/files/5618230/dictionary.txt)

**Comment by Moving-Light** [comment]
You need to manually refresh it but it can be used as a "backup" for when the main API doesn't show the right data

**Comment by josephdadams** [comment]
Ok. If the TCP connection still triggers a tally change (without the correct data), I could use that as a jumping off point to fire an HTTP GET for this data and then parse it. (Do you know if it does that? Making a bus change triggers empty pvw/pgm to be sent? Or the TCP connection doesn't receive any data at all?)

I will add it to the (ever growing) to do list.

**Comment by Moving-Light** [comment]
It will respond with a JSON array when you make the HTTP GET call.  From what I have encountered, the tally console will not give any update when I make a change to preview/program which means it is not being recognized from the TCP.  The connection is still there but there is an error somewhere with handling the DDR and non `input` sources.  Do you know the code for me to manually query and see the TCP data?  I will try to get a response for you to see what the DDR sources look like.

**Comment by fgolman** [comment]
Might I suggest dropping Kane Peterson at NewTek a line. He is my go-to guy when detailed questions come up regarding TriCaster internals. He's a wealth of knowledge. kpeterson@newtek.com

Fritz Golman


________________________________

**Comment by Moving-Light** [comment]
What are you using to filter the tally data from everything else?  I was just looking at the docs and the DDRs come up as `ddr1` and `ddr2`.  Could it be something with the capitalization?  Could it possibly be `ddr1_a` as I see that in the docs too?

**Comment by Moving-Light** [comment]
One other idea that sounds stupid in my head but could work in the short run could be making an HTTP call in a macro every time that they go on preview/program?

**Comment by josephdadams** [comment]
Tally Arbiter opens a TCP socket to the Tricaster on port `5951` and then sends this command: `<register name="NTK_states"/>`. XML data is returned. The benefit of this approach is that it is event-based from the switcher rather than having to consistently poll the switcher over HTTP for the data.

**Comment by josephdadams** [comment]
You could send an HTTP request in a macro from the Tricaster that does an action in TA, once incoming webhooks is supported in TA.

**Comment by Moving-Light** [comment]
So I found the issue to be that tricaster does not include DDR tally updates in it's API.  Sadly that means that it does not update the preview bus when there is a change that includes DDR.  I did have the idea to use Companion as a passthrough to do OSC but for the amount of time to make buttons and macros to do this.  Is there any updates in incoming webhooks?  Thanks again!

**Comment by josephdadams** [comment]
I haven’t done any work on incoming webhooks. I’m still mostly taking on hired work at the moment.
