### ISSUE TITLE
Listeners Wont Connect

### ISSUE THREAD

**Issue by crazytechkid** [josephdadams/TallyArbiter#246]
I open the webpage with the QR code and it just times out. It says an unexpected error occurred. All of the devices are on the same network and the tally works as normal, I just can't connect with my phone. Any ideas?

Using a MacBook Pro laptop and apple phones with an ATEM Mini extreme

**Comment by crazytechkid** [comment]
I am using the local IP that I get assigned from the network

**Comment by hrueger** [comment]
Can you try to ping the Mac from another computer on the same network? Open a terminal there and type `ping 192.10.1.157` or whatever your IP is.

If that succeeds, we know that the network works. In that case it is probably an issue of TA. If the ping fails, something with your network / firewall? is wrong.
