### ISSUE TITLE
tallyarbiter crash when close vmix

### ISSUE THREAD

**Issue by alverman** [josephdadams/TallyArbiter#28]
Tallyarbiter crash when close vmix program or is not online and his is set to connect and or reconnect

**Comment by josephdadams** [comment]
Which version of Tally Arbiter, and what error message do you get?

**Comment by alverman** [comment]
At the moment everything works regularly.
I probably had something wrong with it
Thanks

**Comment by josephdadams** [comment]
Feel free to reopen if that changes. 😃
