### ISSUE TITLE
[Bug]: ESP-32 not detected

### ISSUE THREAD

**Issue by pouarakas** [josephdadams/TallyArbiter#283]
### What happened?

Hi,

I'm trying to connect an ESP32 neopixel as a listener, but the connexion seems to fail. 

The DeviceId stays unassigned and no listener is detected in app and nothing in logs.

Win10 app, not tried with other distrib.

Thanks

### Version

2.0.16

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
[07:50:04]*wm:[1] AutoConnect: SUCCESS 
[07:50:04]*wm:[1] STA IP Address: 192.168.0.104
[07:50:04]connected...yay :)
[07:50:04]Connecting to Tally Arbiter host: 192.168.0.100
[07:50:29]Connected to Tally Arbiter server.
[07:50:29]DeviceId: unassigned
```

**Comment by josephdadams** [comment]
Thank you for submitting this. I’ve received many reports of this same problem. Perhaps we’ve fixed it in 3.0 @MatteoGheza ?

**Comment by MatteoGheza** [comment]
Yes, we re-implemented listener connection and deviceID assignment.
@pouarakas what version of Listener Client are you using? When you updated it the last time?
Maybe you are running the latest listener client firmware version (that you can find in this repository) with an old version of TallyArbiter, which is incompatible with new firmware.

**Comment by pouarakas** [comment]
Hi, I use all the latest versions available.
I tried this morning checking for latest updates and reinstalling the desktop version.

**Comment by MatteoGheza** [comment]
Same as #288 
Please try using our new beta release (v3.0.1) or downgrade you listener client version.
