### ISSUE TITLE
[Bug]: Fix TTGO build

### ISSUE THREAD

**Issue by MatteoGheza** [josephdadams/TallyArbiter#287]
### What happened?

TTGO Github Actions builds works, but without the display.
I'm working on an automated path for TFT_eSPI lib.

### Version

v3.0.1

### Distribution

Desktop

### OS

Linux

### What browsers are you seeing the problem on?

Chrome

**Comment by josephdadams** [comment]
I noticed for the atom builds, and I assume it’s the same for all the esp variants, it comes hard coded with a TA server IP of 192.168.0.110 or something. Which then gets compiled into the binaries we offer for download. This makes them not too useful, right?

**Comment by MatteoGheza** [comment]
Yes, hard-coding the host is useless.
I think that we can replace host setting page with MDNS discovery (or leaving it as "manual setting mode" but adding MDNS).
I'll remove hard-coded IPs when I finish working on flashing devices from UI.

**Comment by josephdadams** [comment]
I like what some of the other various esp projects do where they run either a captive portal or a separate SSID on first boot where you can then put in all this config info. MDNS is good. I also anticipate where I might want the device on wifi but connecting to my cloud instance of TA where MDNS would not apply. So the field needs to support both IP and domain name.

**Comment by mg-1999** [comment]
The Atom builds do have a captive portal at the moment, when it can't find the ssid to connect to it will startup an AP where you can change the settings

**Comment by MatteoGheza** [comment]
Fixed in #358
