### ISSUE TITLE
[Bug]: M5 Atom Matrix Colors Reversed

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#291]
### What happened?

When displaying preview, the web interface shows green as expected, but the M5 shows red. Likewise, for program the web shows red, but the M5 shows green.

Looking at the code, it assumes M5.dis.drawpix write color order is rgb. It's actually grb. Tested locally and it works fine. I'll submit a code change. Note probably also explains why I was seeing lavender as the default color.

### Version

v3.0.1

### Distribution

Desktop

### OS

Linux

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by josephdadams** [comment]
Thanks for fixing!
