### ISSUE TITLE
M5Stick no connect to TA

### ISSUE THREAD

**Issue by alverman** [josephdadams/TallyArbiter#30]
Today I got two M5s and I immediately tried to install the m5 listener but unfortunately it doesn't work.
I configured TA ip and connected to the common wifi.
M5 connects to wifi, shows TA address and port but in TallyArbiter I don't see it.
I had a problem with the SocketIoClient arduino library.
I had to delete line 41 which contains hexdump in the library's SocketIoClient.cpp because it gave me an error in compiling.
I don't think that's what creates the problem.
Some advice ?
Thanks, Alberto

**Comment by josephdadams** [comment]
If you connect an m5 to your computer and run serial monitor, does it show any data being received?

**Comment by alverman** [comment]
I see this:
IM5StickC initializzing...OK
Tally Arbiter M5StickC Listener Client booting.
Connecting to SSID: PS100WiFi
Network connected!
3623878666
Connecting to Tally Arbiter host: 10.0.0.211
[SIoC} Connected to url: /socket.io/?transport=websocket
[SIoC] Disconnected!
[SIoC} Connected to url: /socket.io/?transport=websocket
[SIoC] Disconnected!
[SIoC} Connected to url: /socket.io/?transport=websocket
[SIoC] Disconnected!
[SIoC} Connected to url: /socket.io/?transport=websocket
[SIoC] Disconnected!
[SIoC} Connected to url: /socket.io/?transport=websocket
[SIoC] Disconnected!
........
and so it continues to infinity.
In TA I don't see any connections and disconnections to the M5

**Comment by alverman** [comment]
I can't understand why in the arduino ide the SocketIoClient.h library I don't see it in orange color.
Yet it is filled out regularly

**Comment by josephdadams** [comment]
Which version of TA is this?

**Comment by alverman** [comment]
1.4 
where find 1.3 ?

Thanks, Alberto

**Comment by josephdadams** [comment]
Do you know which socket.io version you are using on the m5 stick? I noticed a new version came out recently which is not compatible with the socket.io version the TA server is running (socketio 2.3).

Here is the link to TA 1.3, although I don't suspect that is your issue: https://github.com/josephdadams/TallyArbiter/tree/c4a9ab24715b0a0c3e57fa7ec2dee4f3422eb7fa

**Comment by alverman** [comment]
On M5 I use lib version 0.1.0
I also tried with the upper library but it doesn't work.
One thing is not clear to me.
When the litener goes running on the server should I automatically see that tally no?
I tried to set up a tally with a raspberry PI 2 and that as soon as it starts I see it in the server and it works correctly.
Now I am preparing two tally with PI Zero but at the moment not even those are working.
I'm freaking out :D

**Comment by alverman** [comment]
I managed to get the two PI Zeros to work but M5Stick doesn't want to know.
Another question: I have a handful of nodemcu and wish I could use them.
Isn't there a code that interfaces to tallyarbiter?
Thanks, Alberto

**Comment by josephdadams** [comment]
I don’t know anything about nodemcu. But the Tally Arbiter protocol is well documented if you want to code your own listener client that does what you need.

**Comment by josephdadams** [comment]
@alverman did you get the m5 sticks to connect? Can I close this issue?

**Comment by lategreat** [comment]
I'm having the same issue. it lookslike its connected but stays unassigned
