### ISSUE TITLE
[Feature Request]: Merging Tally arbiter with into Companion 

### ISSUE THREAD

**Issue by hadphild** [josephdadams/TallyArbiter#309]
### What feature would you like to see added to TallyArbiter?

 Merging Tally arbiter with into Companion

**Comment by josephdadams** [comment]
Why would we want to do this?

**Comment by JTF4** [comment]
Hello @hadphild!

Are you asking about merging the companion and Tally Arbiter projects?

I do not think this is a good idea. 

Companion and TallyArbiter are two very different projects. 


Companion is an open source shotbox software. It controls many things including tally arbiter. It's primary purpose is to control things in a user friendly way. 

Tally Arbiter is an open source tally software. It arbitrates tally data between switchers and clients. Companion is one of those clients. It's primary purpose is to arbitrate tally in a user friendly way. 

I do not see the advantage of combining two pieces of software with very different use cases. 

That not even to mention the fact that TallyArbiter's back end is coded in TypeScript with classes and companion's back end is JavaScript and ES6 functions. 

And on top of that the UI is completely different. Tally Arbiter running an angular ui and Companion is running a React UI. Angular and React are vastly different things to code. 

From both user and developer standpoints, merging the two projects would not be beneficial.

**Comment by hadphild** [comment]
Sorry, this one is a crazy idea. I just want a RPI to build with Companion and TA as a Universal build.

**Comment by mg-1999** [comment]
Alternatively you can use the companion pi build, install npm and do 'npm i tallyarbiter' and still have both on one pi
