### ISSUE TITLE
Flash on led work but not work when change input from vmix

### ISSUE THREAD

**Issue by alverman** [josephdadams/TallyArbiter#31]
I use TA 1.4 on two PI Zeros and from a browser I see that it works correctly.
When I connect them after a while I see them connected in TA
Today I tried to connect two leds to pin 20 and 21 to see the status exchange but when, for example on vmix, I swap the inputs, no led lights up.
While in TA I see the correct exchange between red and green.
If I launch a flash from TA I see the two LEDs flashing correctly.
Where am I wrong?
Thanks, Alberto

**Comment by josephdadams** [comment]
Did you get it working?
