### ISSUE TITLE
[Bug]:  OBS invisible sceneitems 

### ISSUE THREAD

**Issue by Cypris2010** [josephdadams/TallyArbiter#318]
### What happened?

Don't know if this is a bug or it its itended to be:

TallyArbiter does not check for the visibility of the obs sceneitems. It seems to only check if something is in a scene.

### Version

3.01

### Distribution

Docker

### OS

Linux

**Comment by MatteoGheza** [comment]
It's a bug, not a wanted feature, so I'm gonna fix it ASAP.
