### ISSUE TITLE
[Bug]: Relay Listener does not hold a value and turns on and off rapidly

### ISSUE THREAD

**Issue by JTF4** [josephdadams/TallyArbiter#322]
### What happened?

When you put a camera in preview or program, the listener will make the relay turn on and off super fast so the light on the camera just strobes.

### Version

3.0.1

### Distribution

Desktop

### OS

Linux

**Comment by josephdadams** [comment]
It gets their attention though, so I call that a win?

**Comment by JTF4** [comment]
Who needs relays that work anyway?

**Comment by JTF4** [comment]
#324
