### ISSUE TITLE
[Feature Request]: Support the ATEM via USB

### ISSUE THREAD

**Issue by abourget** [josephdadams/TallyArbiter#328]
### What feature would you like to see added to TallyArbiter?

I noticed to add an ATEM, I need an IP address. But it seems I don't have such an IP when the ATEM is connected via the USB port.

Is it even possible to interact with the ATEM when connected via USB?

Thanks for everything!

**Comment by MatteoGheza** [comment]
I'm sorry, I think this isn't possible right now.
The library we are using to interface with ATEMs, [atem-connection](https://www.npmjs.com/package/atem-connection), currently doesn't support USB, since it work differently then network comunication with Blackmagic ATEM.
@hrueger what do you think about this?

**Comment by hrueger** [comment]
Yeah, you're right. I found a repo where @Julusian hast tried to connect to the ATEM via USB, but if you take a look at the readme https://github.com/Julusian/atem-usb-connection it has a lot of (probably unsolvable) problems like replacing the USB drivers on windows.
I don't think that's worth it.

Why don't you want to use the network connection? If you use any other listener client than the web listener on the same laptop, you need a network anyway.

**Comment by abourget** [comment]
It just means I need to have an RJ-45 port, which slightly complexifies the setup, but I agree it's only a slight inconvenience. The new macs have the ports back, but not Ethernet :)
Thanks for the answers, I hadn't found it while searching, so perhaps it can also serve as an answer to the next folks looking for the same thing :)
