### ISSUE TITLE
[Bug]: M5StickC doesn't appear under Connected Listeners

### ISSUE THREAD

**Issue by Hybrikon** [josephdadams/TallyArbiter#340]
### What happened?

I have 3 M5StickC, connected to the AP but I cannot see them in Tally Arbiter. The Log says "Connected to Tally arbiter Server" and DeviceId: unassigned.

Tally Arbiter Works on a MacMini M1

### Version

2.0.16

### Distribution

Desktop

### OS

MacOS

### What browsers are you seeing the problem on?

Chrome

**Comment by mg-1999** [comment]
Did you update to the latest version of TA? The current clients are only compatible with > 3.x.x

**Comment by validlogin** [comment]
We seem to be having a similar issue on TA 3.0.1 and the M5Atom. We see a "Listener Client Connected. Type: m5Atom" in the log but nothing ever pops up under listener clients. On top of that, it doesn't seem like any tally information goes through to the M5Atoms. We have a green check mark and can select the #/ID, but tally never works. 

Interestingly, we tried our other solution (using a m5atom as a vmix via https://github.com/MarkGaretz/ATOM-Matrix-Tally-Light) and TA recognizes a Vmix connection but no tally feedback either. Maybe we're missing something here?

We also tried TA 2 with both solutions with no luck...

**Comment by torstenwild** [comment]
We seem to have the same issue with TA 2.0.16 but also checked 3.0.1  with no difference. 
The m5 atom matrix listeners runs together with another TA installation, but did not figure out whats the clue.

**Comment by mg-1999** [comment]
On what kind of system are you running the TA server? And what does the logger in the Arduino IDE spill out?

**Comment by edbneutron** [comment]
Hi,
I am having the same issue...
M5 Atom and TA 2.0.16 on Windows 10.

I can access TA via webbrowser from android or ipad, 
Serial log of the M5 
---------------------------------
Connected to Tally Arbiter host: 192.168.8.12
deviceObj = {"deviceId": "unassigned", "listenerType": "m5Atom-615033257234764", "canBeReassigned": true, "canBeFlashed": true, "supportsChat": false }
DeviceId = unassigned
["listenerclient_connect",{"deviceId": "unassigned", "listenerType": "m5Atom-615033257234764", "canBeReassigned": true, "canBeFlashed": true, "supportsChat": false }]
charDeviceObj = {"deviceId": "unassigned", "listenerType": "m5Atom-615033257234764", "canBeReassigned": true, "canBeFlashed": true, "supportsChat": false }
---------------------------------

The m5 never turns up in the Tally Arbiter setup..
Any hints?

**Comment by Cypris2010** [comment]
I have the same Problem: The Serial monitor says the following
`rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
M5Atom initializing...OK
Device code: 962c8c
Initializing...
Reading preferences
[  1452][E][Preferences.cpp:483] getString(): nvs_get_str len fail: ta_deviceId NOT_FOUND



*wm:[2] Added Parameter: host
*wm:[2] Added Parameter: port
*wm:[1] AutoConnect 
*wm:[2] ESP32 event handler enabled 
*wm:[2] Connecting as wifi client... 
*wm:[2] setSTAConfig static ip not set, skipping 
*wm:[1] Connecting to SAVED AP: ccc222_24
*wm:[1] connectTimeout not set, ESP waitForConnectResult... 
*wm:[2] Connection result: WL_CONNECTED
*wm:[1] AutoConnect: SUCCESS 
*wm:[2] Connected in 2938 ms
*wm:[1] STA IP Address: 192.168.178.154
Connected to the WiFi... yeey :)
Connecting to 192.168.178.58:4455
[IOc] Connected to url: /socket.io/?EIO=3
["listenerclient_connect",{"deviceId":"","listenerType":"m5atom-962c8c","canBeReassigned":true,"canBeFlashed":true,"supportsChat":true}]
[IOc] Disconnected!
`

**Comment by abunight** [comment]
I have the same error, Atom and Stick-CPlus are connected in the logging but dont appear under listeners tab... Maybe I should enter some stuff in the ino to this:
String DeviceId = "00000001";
String DeviceName = "TallyStick-01";
String LastMessage = "";

?

Did someone find a sollution for this problem?
