### ISSUE TITLE
gpio dont change state in listener

### ISSUE THREAD

**Issue by alverman** [josephdadams/TallyArbiter#36]
Hi, with the new changes the listener is not getting the information for the tally status.
In fact, the gpio status change messages do not appear in the console

**Comment by josephdadams** [comment]
Which listener client?

**Comment by alverman** [comment]
tallyarbiter-gpolistener.py

**Comment by josephdadams** [comment]
Make sure that the GPO listener is NOT using the latest version of Python socketio client. A version increase was done recently and it’s not compatible with the tally arbiter server. You have to be on version 4 I believe.

**Comment by josephdadams** [comment]
@alverman did you get it working?
