### ISSUE TITLE
[Bug]: M5StickCPlus two issues with 3.0.1

### ISSUE THREAD

**Issue by Fred-DTV** [josephdadams/TallyArbiter#362]
### What happened?

Just testing our M5StickCPlus with the current TA version 3.0.1

Several problems I found:

- static IP settings are gone
- LED_preview & LED_program don't work properly 

I've set Tally_EXTRA_OUTPUT to true and tried several LOW/HIGH Settings for the LEDs but nothing seemed to work right.
Additionally I think that the first if statement should be "program"
`    #if TALLY_EXTRA_OUTPUT
    if (actualType == "preview") {
      digitalWrite(led_program, LOW);
      digitalWrite (led_preview, LOW);
      digitalWrite (led_aux, HIGH);
    } else if (actualType == "preview") {
      digitalWrite(led_program, HIGH);
      digitalWrite (led_preview, HIGH);
      digitalWrite (led_aux, HIGH);
    } else if (actualType == "aux") {
      digitalWrite(led_program, HIGH);
      digitalWrite (led_preview, LOW);
      digitalWrite (led_aux, LOW);
    } else {
      digitalWrite(led_program, HIGH);
      digitalWrite (led_preview, LOW);
      digitalWrite (led_aux, HIGH);
    }
    #endif`

### Version

3.0.1

### Distribution

Desktop

### OS

Windows

**Comment by JTF4** [comment]
Hey @DachsbauTV!

Have a look at the new listener client. We pushed an update that should fix those issues.

**Comment by Jocke4f** [comment]
Using TALLY_EXTRA_OUTPUT now works. Earlier was the wrong pin specified but this has earlier been fixed. One key thing is the that the image is hardware version specific so using a m5stickc plus bin on a m5stickc doesn't work. I haven't tracked backward to when it was fixed but it works on the listener built on v3.0.10 tag.
