### ISSUE TITLE
Remove references to contact me through blog

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#363]
### What feature would you like to see added to TallyArbiter?

We need to comb through the various repos and documentation and remove any encouragement to contact me directly through my blog. I'm not shutting down the blog nor am I walking away from this project - I just need people to be filing issues here and not emailing me so much where things cannot get tracked. I get several emails a week that I don't have time to respond to.

**Comment by wrldtvlr** [comment]
You may want to make a quick pass through YouTube. There are references to tech ministry blog there as well. https://www.youtube.com/watch?v=msfAL631ARw

**Comment by mg-1999** [comment]
The default reply on issues and pull request has a reference to the blog and should be removed

**Comment by mark-epstein** [comment]
I for one LIKE the links to the blog. Once I realized how much quality @josephdadams puts into his work, I wanted to check out other projects whether or not I had a need for them.  And people might just want to send an encouraging word, I'd say the blog is an ideal place for that.

I'd suggest a big warning on the blog that says "this is not the place to report your tech support issues!" Then give them the right links.

**Comment by JTF4** [comment]
What if we reword things then.

"To [report a bug](https://github.com/josephdadams/TallyArbiter/issues/new?assignees=JTF4&labels=bug&template=bug.yaml&title=%5BBug%5D%3A+) or open a [feature request](https://github.com/josephdadams/TallyArbiter/issues/new?assignees=JTF4&labels=feature&template=feature.yaml&title=%5BFeature+Request%5D%3A+), please do so on our [issues](https://github.com/josephdadams/TallyArbiter/issues/new/choose) page."

"If you would like to see more of @josephdadams's projects or send a word of encouragement his way, please visit [techministry.blog](https://techministry.blog/)."
