### ISSUE TITLE
Error: read ECONNRESET with Webhook action

### ISSUE THREAD

**Issue by corndog2000** [josephdadams/TallyArbiter#37]
I have a simple Tally Arbiter setup with two OBS color sources that I am switching between in Studio mode. I have one light setup with four actions Program/Preview both with On/Off. When I switch between the color sources the console window prints out some errors. My tally light that I am controlling with the actions is an ESP32 and is using the script recommended in the Readme (TallyArbiter-arduino-neopixel). It is connected with the webhook action.

"An error occured triggering the Outgoing Webhook: Error: read ECONNRESET"

It's like Tally Arbiter fails to send one or two webhook signals to the device when switching sources in OBS.

**Comment by josephdadams** [comment]
Econnreset happens when the other end of the socket (in this case the esp32) abruptly ends the tcp session. It could be because the esp32 code doesn’t properly end socket connections, or it’s just getting overloaded. Try opening an issue on that repository for the esp32 and see if it can get sorted out there.

Does it happen every time or only when it gets busy?

**Comment by corndog2000** [comment]
It seems to have one or two errors when it's the program on action happens. The preview off action is correctly send but the program on one errors out. I figured that the esp32 might be to blame. I'll cross reference the code with your code for the M5stick.

**Comment by josephdadams** [comment]
Check with @NoahCallaway for the neopixel esp32 project.

**Comment by NoahCallaway** [comment]
Hiya! The script was written for an esp8266 and uses the libraries for it. I'm not sure how well these work on an esp32... I don't have one to test. 
For troubleshooting and testing it should be serving a little webpage where you can test functionality without Tally Arbiter. If you go to the IP address or hostname in your browser it should load a webpage like this.
<img width="337" alt="Screenshot 2020-12-28 at 20 40 29" src="https://user-images.githubusercontent.com/24882928/103411726-66022d00-4b69-11eb-8a88-64d3109a4caf.png">

Can you get to this? And can you successfully control the light by changing values?

**Comment by corndog2000** [comment]
I know the original sketch is for the esp8266. I have gone through and updated the included libraries to be the matching esp32 libraries and updated some of the MDNS code. The code works fine with the local webpage. It also works with Tally Arbiter but only when you send one command at a time. The error happens when Tally Arbiter tries to send "Preview Off" and "Program On" very quickly.

**Comment by corndog2000** [comment]
I have the modified code on GitHub here: https://github.com/corndog2000/TallyArbiter-arduino-neopixel

**Comment by NoahCallaway** [comment]
Ahh right I see I only really use program not preview in my setup. Are you using the hostname or IP address in TallyArbiter's action configuration? I found the IP address worked much better.

**Comment by corndog2000** [comment]
Yea, I noticed that the IP address has a higher success rate. The error message still happens while using the IP address.

**Comment by NoahCallaway** [comment]
Ahh I see. I can't recreate the fault consistently here using 2 groups both with program and preview... Could probably look at implementing Socket.io similar to how the M5 Stick script does but don't think that will allow for multiple tally lights from one ESP which is what this script was originally designed for.

It's probably worth us creating a new version using web sockets designed for a single tally light.

**Comment by corndog2000** [comment]
Would you be able to share an example of your working setup? I keep getting an connection reset error when Tally Arbiter tries to send two POST messages. The first one works but the second one always errors out.

**Comment by NoahCallaway** [comment]
There you go. That's one of the two I have configured. The second one is identical but uses `&group=2`

<img width="506" alt="Screenshot 2020-12-31 at 20 47 09" src="https://user-images.githubusercontent.com/24882928/103425313-72a67580-4ba9-11eb-9568-600605242322.png">

The POST Data is `led=ON&red=255&green=0&blue=0&group=1` for Program ON.

**Comment by corndog2000** [comment]
I got it working by changing the RunAction_Webhook function to use the http library instead of axios. Perhaps the ESP32 webserver library doesn't work well with axios messages. Thanks for the troubleshooting help.

**Comment by josephdadams** [comment]
You can maintain your fork if you want, or it might be better to figure out what is needed to make the existing library work (or change libraries).

**Comment by corndog2000** [comment]
I wasn't sure if my change would break some other webhook applications.
