### ISSUE TITLE
Local GPO-listener unable to connect

### ISSUE THREAD

**Issue by evenover** [josephdadams/TallyArbiter#38]
Hi!
I'm quite new to code so it's probably just a minor issue with my setup. I've tried both localhost and running the server on another computer and i still get the same error. Downgraded the socket.IO to the version recommended. I want to run the server and listener on the same Pi.

I'm getting the error:

Unable to connect to Tally Arbiter server: 127.0.0.1 4455
Traceback (most recent call last):
File "tallyarbiter-gpolistener.py", line 165, in
sio.connect('http://' + server_config['ip'] + ':' + str(server_config['port']))
File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 284, in connect
raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: Connection refused by the server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "tallyarbiter-gpolistener.py", line 173, in
time.sleep(15)
File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 39, in signal_handler
return original_signal_handler(sig, frame)
File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 26, in signal_handler
return original_signal_handler(sig, frame)
KeyboardInterrupt

**Comment by corndog2000** [comment]
Did you find a solution to this issue? I am having the same problem.

**Comment by evenover** [comment]
I was only downgrading the server socket.io and not the client.
Just uninstall the client with
sudo pip3 uninstall python-socketio[client]

and install the last version 4 client with
sudo pip3 install python-socketio==4.6.1

**Comment by josephdadams** [comment]
Sorry about this. I’ll be working to get everything brought up to the latest socketio ASAP.
