### ISSUE TITLE
Control of ATEM via OSC

### ISSUE THREAD

**Issue by Wilts01** [josephdadams/TallyArbiter#39]
At the moment my church set up is using atemOSC to control our ATEM 4K Pro when videos are played out from a PC.  I'm using ShowCueSystems on the PC and when I run the cue on the PC, it sends OSC commands to atemOSC which switches the ATEM preview bus to be the feed from the PC and then runs the currently selected auto transition.  At the end of the video, it runs another auto transition.  

I'd like to deploy TallyArbiter as well but am mindful of the limited number of connections that the ATEM supports so is there any scope for replicating the basic behaviour of atemOSC in TallyArbiter - ie tell it to select a given input as program and/or preview and then either cut/auto transition?

**Comment by josephdadams** [comment]
This is definitely outside the scope of Tally Arbiter and not something we would and to implement. I believe most ATEMs can handle 5 connections at a time, so if it’s just atemOSC and Tally Arbiter, you should be fine.

**Comment by Keksstar** [comment]
You will need something like an Skaarhoj ATEM Proxy, which allows more than five connections to the ATEM.
https://www.skaarhoj.com/back-catalog/atem-proxy/
