### ISSUE TITLE
[Bug]: ATOM doesn't appear on listeners list

### ISSUE THREAD

**Issue by Pirrao** [josephdadams/TallyArbiter#391]
### What happened?

ATOM Matrix doesn't appear on the connected devices list, the serial port from the ATOM says it is connected but it doesn't appear on the list and can't address any camera to de tally.

### Version

2.0.6

### Distribution

Desktop

### OS

Windows

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by hrueger** [comment]
Hi, what firmware are you using for the ATOM? The one from this repository? Then, it might only be compatible with Tally Arbiter version 3.

**Comment by JTF4** [comment]
@Pirrao I'm not 100% sure what you're asking about here. If your wanting a static IP on a M5Stick, you can download the ino file and follow the directions in it to configure a static IP.

**Comment by stefansnelgrove** [comment]
Having same issue

**Comment by Jocke4f** [comment]
Closing this since it works on TA v3.0.10 with ATEM running latest listener code. I have not tested TA v2 with v2 version of the listener.
