### ISSUE TITLE
Add message system....

### ISSUE THREAD

**Issue by houtacheng** [josephdadams/TallyArbiter#4]
Text can be passed between the host and the client. There are some default buttons such as zoom in / zoom out / pan left ect...

**Comment by josephdadams** [comment]
This is on the to do list! I hope to implement it in an upcoming release shortly.

**Comment by houtacheng** [comment]
Looking forward to it.

**Comment by josephdadams** [comment]
@houtacheng there is now a simple messaging feature. No default buttons as of yet, but perhaps in a future version. Currently you can only message the web tally viewer clients, but I may add support for other clients that can deal with text at a later date.

**Comment by houtacheng** [comment]
i cannot wait for it!

**Comment by MatteoGheza** [comment]
@josephdadams is there any TODO?

**Comment by josephdadams** [comment]
@MatteoGheza any enhancements you like. I used it for awhile recently for a chat experience and found it would be nice if:
- you could set a chat nickname
- A small sound was made when new messages arrived

I had also envisioned simple buttons like @houtacheng originally asked for, perhaps user definable in some way.

**Comment by hrueger** [comment]
It would also be cool if messages were persistent and therefore still shown after a restart. But then werden probably also need a clear chat button.

**Comment by josephdadams** [comment]
I’m open to any and all enhancements that could make it more usable. I know not a lot of people use it, but for those that need it, it’s sure nice to have something integrated. I would even be fine with using a chat library if such a package exists.

**Comment by peterfdej** [comment]
Can a listener send back a message? if so, how to do it?
I have integrated in my TTGO-T-display listener a Sony LANC interface for communication with a Sony camera (zoom and record) and a TCP server for remote PTZ control. I want to send back to the producer when a camera is recording or not. (LANC protocol 4th byte returns 0xFB record is on, 0xEB record is off)

**Comment by josephdadams** [comment]
Right now it is limited to socket.io communication. I suppose if you implemented that on your listener, it could join the chat room and send back messages.

**Comment by peterfdej** [comment]
I managed it this way:
void SendMessage(String message) {
  String deviceObj = "\""+DeviceName+"\",\""+message+"\"";
  char charDeviceObj[1024];
  strcpy(charDeviceObj, deviceObj.c_str());
  ws_emit("messaging", charDeviceObj);
}
