### ISSUE TITLE
"Manual" source?!

### ISSUE THREAD

**Issue by ben-bole** [josephdadams/TallyArbiter#404]
Hey there,
I am currently planning a charity concert livestream, for which I need at least one tally light (via smartphone display)
TallyArbiter basically provides more than enough capabilities for what I need. Because I have a very uncommon video mixer (RGBlink mini+) with no expansion/ scripting/ TSL components.  I am searching for a "manual" source in TallyArbiter.
Is there maybe some way to implement a dummy switch? Or a simple command line script that just sends the TSL payload? 
The documentation for the TSL protocol is hard to understand for non AV-people, so I decided to ask here, whether someone maybe already implemented such a thing.

Thanks in advance, Benedict

**Comment by josephdadams** [comment]
Tally Arbiter supports OSC, you could easily use this for triggering. @hrueger did we ever finish the manual test mode?

**Comment by hrueger** [comment]
Hm, I don't think so. I can add that, because it would be quite a useful feature, but as I said in the other Issue, I won't be able to do this in the next two months.

**Comment by hrueger** [comment]
@ben-bole You could use companion for this. You don't even need a StreamDeck as the web emulator should work just fine.

**Comment by JTF4** [comment]
@ben-bole 

Have a look at this documentation page. If you use the OSC calls you can manually trigger a tally device. 

https://josephdadams.github.io/TallyArbiter/docs/usage/sections/sources

Like @hrueger said, you can easily use companion with the web emulator to send the OSC, or you can use any other method of sending OSC.

**Comment by ben-bole** [comment]
> Hm, I don't think so. I can add that, because it would be quite a useful feature, but as I said in the other Issue, I won't be able to do this in the next two months.

That would be really useful!
In the meantime I am going to use Companion and send TSL calls from there 😇
