### ISSUE TITLE
Reconnect Connected Listeners

### ISSUE THREAD

**Issue by audioteck** [josephdadams/TallyArbiter#41]
I have setup 4 m5stick's with static IP addresses. I would love to be able to mark them in the Connected Listeners list to be persistent so when they are Reconnected they are assigned to the previously assigned Device instead of the first device. This is also for a church. Really love your software!!!! Also I used the m5stickCplus library (I mistakenly bought pluses) and it worked fine...

**Comment by josephdadams** [comment]
I just implemented this today. Update your TA server and update all your sticks to the latest client. 😃

**Comment by audioteck** [comment]
Awesome. What's the best was to update the server. Just reinstall???

**Comment by josephdadams** [comment]
https://github.com/josephdadams/TallyArbiter#upgrading-the-software

It mostly depends on your OS and how you installed it originally. Just back up your config.json file or you will lose your config!
