### ISSUE TITLE
OBS not in Studio mode

### ISSUE THREAD

**Issue by fbosman** [josephdadams/TallyArbiter#42]
Hi,
I love this program and would like to use it.
However, we are using OBS not in studio-mode, just switching sources through companion on and off.
TallyArbiter only reacts on sources when OBS is in studio mode.
Can this be enhanced?

regards

Frans

**Comment by josephdadams** [comment]
This shouldn’t be the case. I’ll test it here as I also don’t use OBS in studio mode. It should basically only do PGM only. It used to be that way, so either there’s a bug or you’re doing something wrong. :)

**Comment by fbosman** [comment]
Maybe I’m doing something wrong...

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 11 jan. 2021 om 13:02 heeft Joseph Adams <notifications@github.com> het volgende geschreven:

﻿
This shouldn’t be the case. I’ll test it here as I also don’t use OBS in studio mode. It should basically only do PGM only. It used to be that way, so either there’s a bug or you’re doing something wrong. :)

**Comment by josephdadams** [comment]
Working as expected here. So let's work through your setup. I'm assuming you're using the latest version of Tally Arbiter. Are you keeping the device sources unlinked or are you linking them to something else? The default is unlinked so you would have to add another source type and specifically choose to do this.

**Comment by fbosman** [comment]
Hi Joseph,
It was a complete fresh install on my MacBook m1.

Clean node.js, clean tallyarbiter, clean Obs.

It all works when I am in studio mode, but not when I’m not.

Currently I’m not at my setup, it may take some hours...

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 11 jan. 2021 om 16:20 heeft Joseph Adams <notifications@github.com> het volgende geschreven:

﻿
Working as expected here. So let's work through your setup. I'm assuming you're using the latest version of Tally Arbiter. Are you keeping the device sources unlinked or are you linking them to something else? The default is unlinked so you would have to add another source type and specifically choose to do this.

**Comment by josephdadams** [comment]
I'll have to upgrade to the latest OBS and websocket plugin to rule those out. Send me your config file.

**Comment by fbosman** [comment]
I tested it on my windows-10 machine and got the samen results.

 

Config:

 

{

"security": {

  "username_settings": "admin",

  "password_settings": "12345",

  "username_producer": "producer",

  "password_producer": "12345"

},

"sources": [

  {

   "sourceTypeId": "4eb73542",

   "enabled": true,

   "name": "obs",

   "reconnect": true,

   "data": {

    "ip": "localhost",

    "port": "4444",

    "password": ""

   },

   "id": "b0d6a6e1",

   "connected": true

  }

],

"devices": [

  {

   "name": "rrr",

   "description": "rrr",

   "tslAddress": "",

   "enabled": true,

  "id": "efdeae8f",

   "linkedPreview": false,

   "linkedProgram": false

  },

  {

   "name": "in",

   "description": "in",

   "tslAddress": "",

   "enabled": true,

   "id": "428f8458",

   "linkedPreview": true,

   "linkedProgram": true

  }

],

"device_sources": [

  {

   "deviceId": "efdeae8f",

   "sourceId": "b0d6a6e1",

   "address": "Extra film",

   "id": "4dcb689e"

  },

  {

   "deviceId": "428f8458",

   "sourceId": "b0d6a6e1",

   "address": "misintenties",

   "id": "a364a1a9"

  }

],

"device_actions": [],

"tsl_clients": [],

"cloud_destinations": [],

"cloud_keys": []

}

Met vriendelijke groet,

 

Frans Bosman

 

Van: Joseph Adams <notifications@github.com> 
Verzonden: maandag 11 januari 2021 21:53
Aan: josephdadams/TallyArbiter <TallyArbiter@noreply.github.com>
CC: Frans Bosman <frans@fbosman.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [josephdadams/TallyArbiter] OBS not in Studio mode (#42)

 

I'll have to upgrade to the latest OBS and websocket plugin to rule those out. Send me your config file.

**Comment by josephdadams** [comment]
I took your config and applied it here. I upgraded to the latest OBS, 26.1.2 to make sure there wasn't something unexpected happening there.

I created two scenes, `test1` with the source `Extra film`, and `test2` with the source `misintenties`. This matches your two devices and their device sources based on the config file you provided.

The behavior seems normal here in both Studio (pvw and pgm) mode as well as non-Studio (only pgm) mode. It is working as expected.

**Comment by fbosman** [comment]
Hi Joseph,

I think I found the issue.

We are using one scene with several sources and switch these sources on and off.
It seems your great program tests whether a scene is active and not a source as we use them.
Is that right?

Regards,

Frans

**Comment by josephdadams** [comment]
It tracks Scenes or Sources active in the current Scene. So if you're not actually changing Scenes, then the websocket data is not sending any updates that it is tracking.

Are you just using one scene and turning a source on or off (the eye icon)?

**Comment by fbosman** [comment]
Yep, that’s right,
Maybe we should reconsider that

**Comment by josephdadams** [comment]
Try it that way and let me know how it works. I don't see much advantage in your current approach when it is just as easy to make another scene and switch between them.
