### ISSUE TITLE
Allow Companion to switch tally lights

### ISSUE THREAD

**Issue by fbosman** [josephdadams/TallyArbiter#43]
Hi,
We use a ptz-camera as main camera. Companion is used to use presets on this camera. One of these presets is a long distance shot of the organ and choir. Is it possible to set a specific tally for a preset so that the choir can see when the camera is aimed at them?

**Comment by josephdadams** [comment]
Yes. In Companion, you can add an action upon preset recall that uses the Generic OSC module to send OSC to Tally Arbiter for this. Create a new device for each preset, and assign it a device source address for your OSC source in Tally Arbiter.

In TA, create a new OSC source type.

Then create two Devices, `Organ`, and `Choir`. For `Organ`, assign a Device Source of `organ` to your OSC source. Similar with choir.

Then, for your Organ preset recall in Companion, in addition to having the PTZ recall action, you would have the following:

- Generic OSC to TA: `/tally/program_on` with a string argument of `organ`
- Generic OSC to TA: `/tally/program_off` with a string argument of `choir`

Let me know how this goes.

**Comment by fbosman** [comment]
Hi Joseph,

This works great! Thank you!

**Comment by fbosman** [comment]
This works great! Thank you!

**Comment by josephdadams** [comment]
You're welcome!
