### ISSUE TITLE
[Bug]:  gpo-listener cd41434 not clearing preview GPO 

### ISSUE THREAD

**Issue by msberger** [josephdadams/TallyArbiter#432]
### What happened?

gpo-listener cd41434 is not working properly.
it somehow is not clearing preview GPO if switched to a different preview.
preview gpo is only cleared if same group becomes program

### Version

TallyArbiter 3.0.3 / gpo-listener cd41434 

### Distribution

CLI

### OS

Linux

### What browsers are you seeing the problem on?

Chrome

### If applicable, What Listener Clients are You Using?

GPI

**Comment by MatteoGheza** [comment]
I'm really sorry. I was really busy these days.
I updated the listener in 4b87e25 and this bug should be fixed.
Currently, I tested this "logic fix" only in a simple dev env, I don't tried this with a real prod setup.
Can you try it @msberger? Thanks in advance.

**Comment by msberger** [comment]
Thank you for the update.
I did a brief test in small setup and everything looks good.
I think this bug is fixed !
Markus
