### ISSUE TITLE
[Bug]:  Not connecting to ATEM mixers

### ISSUE THREAD

**Issue by Smolinc** [josephdadams/TallyArbiter#448]
### What happened?

Version 3.0.4. When adding a mixer it not connected, the memory overflows and the program closes. 
On version 3.0.3 it connects without problems. But VMix Server does not work. Returned to 2.0.16 everything works.

### Version

3.0.4

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by Smolinc** [comment]
Try on MAC OS the same issue. Memory overflow if add Atem mixer.

**Comment by hrueger** [comment]
Hi @Smolinc,
> When adding a mixer it not connected, the memory overflows and the program closes.

Thanks for the report, we can test this.

> But VMix Server does not work

Can you clarify this? Can you see if vmix emulator is started (the port is being used)? The problem is that I don't have a vMix setup here to test this...

**Comment by Smolinc** [comment]
No on version 3.0.4 Vmix emulator starts up normally. All my clients connected to emulator. I try 3.0.3 version and on it vmix emulator not work, but ATEM mixer connect normally.

**Comment by Jocke4f** [comment]
Is this still an issue with TA v3.0.6? In v3.0.6 an improvement regarding the ATEM handling was included.

**Comment by Jocke4f** [comment]
Marked as close since improvements were included in v3.0.6.
