### ISSUE TITLE
run an older version of TallyArbiter on my server

### ISSUE THREAD

**Issue by mrfanny** [josephdadams/TallyArbiter#449]
### What feature would you like to see added to TallyArbiter?

Hello,

I would like to run version 2.0.16 on my server. When I start this version manually with the npm start command, everything runs fine. But when I follow [https://josephdadams.github.io/TallyArbiter/docs/installation/cli#running-as-a-service](https://josephdadams.github.io/TallyArbiter/docs/installation/cli#running-as-a-service), I add TallyArbiter to pm2 and restart the server, TallyArbiter version 3.0.4 starts automatically. Is there a solution to not running in version 3.0.4 and running only version 2.0.16?

**Comment by JTF4** [comment]
Go ahead and npm remove tallyarbiter. 

Then try `npm install tallyarbiter@1.0.16 -g`
