### ISSUE TITLE
[Bug]: Possible wrong port with Panasonic HS-410 source type

### ISSUE THREAD

**Issue by davekimi14** [josephdadams/TallyArbiter#459]
### What happened?

So trying to setup up the Panasonic HS-410. Had trouble connecting to it so I scanned it with some port scanning software, and I think it is port 60200 instead of 60020. Could you please take a look at this or make the port editable inside the software? Thank you

### Version

2.0.16

### Distribution

Desktop

### OS

Windows

**Comment by josephdadams** [comment]
@davekimi14 if you can run Tally Arbiter from source and confirm the port number, we can change it

**Comment by josephdadams** [comment]
added a port option
