### ISSUE TITLE
[Bug]: no m5 atom matrix listeners found?

### ISSUE THREAD

**Issue by Christoph111** [josephdadams/TallyArbiter#470]
### What happened?

hi, m5 atom matrix listeners work fine with 2.0.16 but they don´t appear in 3.0.4, in serial monitor the don´t receive a device_id.
any idea what has changed here and how to fix it?
Also i can click the atom to change the camera number, but this does not affect anything. Only changes made by TA show tally for the correct camera - but unfortunaley the atom camera number does not change by this TA change....
any ides?
cheers
Christoph

### Version

3.0.4

### Distribution

Desktop

### OS

MacOS

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by josephdadams** [comment]
TA 3.x is only compatible with the new code for listener clients so you will have to update the atom to the latest code. Yes the number is just an aesthetic it doesn’t actually do anything at this time.
