### ISSUE TITLE
[Bug]: 3.0.4 does not recognize atem mini

### ISSUE THREAD

**Issue by Christoph111** [josephdadams/TallyArbiter#471]
### What happened?

hi,

in 2.0.16 my atem mini is found by its IP. In 3.0.4 added manually it stays red (not connected), IP and everything double checked.
When i remember correctly there was also something like auto discover, did not see this at this time...
anyone else has this issue?
cheers

### Version

3.0.4

### Distribution

Desktop

### OS

MacOS

**Comment by sempei13** [comment]
Same problem, but with an ATEM Television Studio HD.

**Comment by zacharysousa** [comment]
The new version works, but you have to build from source.

**Comment by Jocke4f** [comment]
Is this still an issue with TA v3.0.6? In v3.0.6 an improvement regarding the ATEM handling was included.

**Comment by Jocke4f** [comment]
I have tested both v3.0.6 and v3.0.7 ATEM Mini Extreme ISO and ATEM Television Studio without this "not recognize" issue, so it is no longer necessary to build from source.

I suggest that this is closed.
