### ISSUE TITLE
Atem Constellation 2ME not working[Bug]: 

### ISSUE THREAD

**Issue by haeleng** [josephdadams/TallyArbiter#476]
### What happened?

A bug happened! It looks like the Blackmagic Atem Constellation 2ME is not working.
I have added the Constellation to the sources and it colors green.
When I add a device like camera1 it can be added.
When I next do edit sources I can select Constellation as a source.
However the address field stays empty and there is no drop down list.
Switching on the Constellation 2ME does not give a preview or program indication. The PVW and PGM column remains empty
With OBS studio it does work.
Please help

### Version

2.0.16 (latest) stable

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

### TallyArbiter configuration

```javascript
I'm a novice do not know where to find it.
```

**Comment by hrueger** [comment]
The ATEM Constellation 2 ME is so new that the version of the library we're using for connecting to the ATEM does not support it (yet).
I just saw that they updated it a few days ago: https://github.com/nrkno/sofie-atem-connection/blob/HEAD/CHANGELOG.md#300-2022-07-28

We probably just have to update the dependency, then it should hopefully work.

**Comment by gohamstergo** [comment]
+1. any word if this fix will be in the next version?

**Comment by gohamstergo** [comment]
> We probably just have to update the dependency, then it should hopefully work.

is this something that an end user could do to get this to work in the meantime? if you could point me in the right direction, i might be able to figure it out.

**Comment by MatteoGheza** [comment]
The library have been in #501 ([a2061ef](https://github.com/josephdadams/TallyArbiter/pull/501/commits/a2061ef1228b36e77ceb0b7c848db412185d12fb))

**Comment by Julusian** [comment]
I can confirm that the constellation 2ME works with the latest v3 release of tally arbiter

**Comment by gohamstergo** [comment]
> I can confirm that the constellation 2ME works with the latest v3 release of tally arbiter

which version is that? i only see 3.0.4 from May 2022 in the releases.

**Comment by Julusian** [comment]
> > I can confirm that the constellation 2ME works with the latest v3 release of tally arbiter
> 
> which version is that? i only see 3.0.4 from May 2022 in the releases which wasn't working when I last commented.

It was with 3.0.4
