### ISSUE TITLE
Legacy IOS Devices

### ISSUE THREAD

**Issue by mattdscott** [josephdadams/TallyArbiter#48]
What's the latest IOS device thats supported as a Tally device? On iphone 5 or earlier, while the page will load, nothing will populate the dropdown menu. Is there a workaround or have you experienced this before? 

Thanks.

M

**Comment by josephdadams** [comment]
According to this chart (https://caniuse.com/websockets) I would think iOS Safari 4.2 or higher would work. Which is pretty old. And even then, long-polling through socketio would probably work on older browsers.

Make sure you're using the latest version of TA; there's been some issues with the socketio library getting pushed past version 2.3.0 causing connectivity issues.

If you're on the latest TA (1.5.3) and still experiencing this, let's do some more troubleshooting.

**Comment by mattdscott** [comment]
Thanks for getting back to me Joseph!

I checked this AM when I got back to site. We are running the current TA (1.5.3). When load on "Server IP" in safari on iOS (9.3.2), it will load TA (ServerIP:4455/Tally) but I get "No Devices are available for Tally Monitoring at this time".

If I try to login to the settings (ServerIP:4455/Settings) after LOGIN, it shows all the menu structure but no info or devices are there. 

It is working on multiple Fire Tablets and iPhone 7 or earlier.

**Comment by mattdscott** [comment]
On an unrelated note, Having issues getting the plist code to install properly. 
I get a 

[PM2] [ERROR] Failure when trying to write startup script
ENOENT: no such file or directory, open '/users/USERNAME/Library/LaunchAgents/pm2.stream.plist

I'm still digging into this but thinking it my be a permissions issue.

**Comment by josephdadams** [comment]
I guess there is some js that TA is using that is unsupported. I really wasn't expecting that, but I guess we will have to come up with a table for supported devices so people know how old of a phone they can bring.

I'm not sure about that `pm2` error - I mainly only use it on a Pi. Can you try running it sudo?

**Comment by josephdadams** [comment]
@mattdscott can you try creating that plist file manually?

**Comment by wrldtvlr** [comment]
> 
> 
> On an unrelated note, Having issues getting the plist code to install properly.
> I get a
> 
> [PM2] [ERROR] Failure when trying to write startup script
> ENOENT: no such file or directory, open '/users/USERNAME/Library/LaunchAgents/pm2.stream.plist
> 
> I'm still digging into this but thinking it my be a permissions issue.

FWIW, I had a similar permissions problem. Had to open a Big Sur Terminal window, create the user LaunchAgents folder, and then fix all the file/subdirectory permissions with chmod and chown.
