### ISSUE TITLE
Device Name is not displaying on M5StickC [Bug]: 

### ISSUE THREAD

**Issue by commputethis** [josephdadams/TallyArbiter#484]
### What happened?

Device name is not showing on the screen of the M5StickC, but it does on M5StickC Plus.  Everything else seems to be working fine.

### Version

3.0.1

### Distribution

Docker

### OS

Linux

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by JTF4** [comment]
I'll have a look at the code and see if I can find the issue.

**Comment by JTF4** [comment]
@commputethis are you compiling the M5StickC code using the Arduino IDE? Or are you downloading and flashing the bin file to the device?

**Comment by RockNRollGeek** [comment]
I'n actually having the opposite problem - the latest downloadable bin of the m5stickc build works fine after flashing, but flashing the bin to the m5stickc plus seems to work in regards to the AP and connection, but the screen is just a garbled mess. redownloaded, reflashed, confirmed issue still existed on the plus but displays fine on the regular m5stickc.

**Comment by Jocke4f** [comment]
The device name is shown. This was earlie fixed. One key thing is the that the image is hardware version specific so using a m5stickc plus bin on a m5stickc doesn't work. I haven't tracked backward to when it was fixed but it works on the listener built on v3.0.10 tag.
