### ISSUE TITLE
ATEM tally incorrect during a transition

### ISSUE THREAD

**Issue by smadds** [josephdadams/TallyArbiter#50]
This is such a great project!. I love it!

If I start a transition manually on an ATEM Studio HD the PV bank switches to red, but this is not matcher on TA. It only seems to notice at the end of the transition, when the new input hits the program bus. The screenshot shows the 2 reds on the ATEM, but the setup mimic on TA shows a red & green. Is this a problem with the signalling from the ATEM?

FYI my Stream Deck Companion status works fine when linking the button's status to "Change colours from mixer program tally"

 
![image](https://user-images.githubusercontent.com/5259870/106368877-0b651800-6345-11eb-8f85-d01320936916.png)

**Comment by jerriley** [comment]
I noticed this as well. Even after the Mix transition is complete, there is a delay of a second or two before the colors swap in Tally Arbiter (and on the listeners I use). The bug is the same for Auto button transition as well as T-bar transition.

**Comment by josephdadams** [comment]
This should be fixed in latest
