### ISSUE TITLE
[Feature Request]: Update electron to shut down TA on MacOS shutdown/restart

### ISSUE THREAD

**Issue by josephdadams** [josephdadams/TallyArbiter#500]
### What feature would you like to see added to TallyArbiter?

A user has reported that when they shut down their Mac, TA prevents the shutdown process.

We should add a listener and shut it down.

https://stackoverflow.com/questions/51804259/how-to-prevent-electron-app-from-interrupting-macos-system-shutdown

**Comment by Jocke4f** [comment]
Was the fix for this included in https://github.com/josephdadams/TallyArbiter/releases/tag/v3.0.8? If so can we then close this issue?

**Comment by josephdadams** [comment]
yep
