### ISSUE TITLE
Connection error?

### ISSUE THREAD

**Issue by smadds** [josephdadams/TallyArbiter#51]
Not sure what I'm doing wrong, but am having difficulty showing the live status on the Producer information page.

My use case is to offer remote access via port redirection on the router (mapped a public port to local IP of TA port 4455 for TCP). Everything works locally, but I can't get this page to update remotely. 

Are there any other ports I need to redirect?

![image](https://user-images.githubusercontent.com/5259870/106446167-d0173600-6477-11eb-95c6-a9f142aae38f.png)

**Comment by josephdadams** [comment]
You should only have to port forward 4455 as the entire TA service runs on that port. All connections are made over socketio. I have a cloud server running TA that I can connect to with only that port open.

On the off-chance that it helps your issue, I just posted this commit: https://github.com/josephdadams/TallyArbiter/commit/bfb1134231b192f3d902963953159d2fb3d7aa67

It should help with the console error message you posted.

**Comment by smadds** [comment]
Thanks, Joseph. I pulled the new image and the issue has gone.

Happy bunny here - thanks!

![image](https://user-images.githubusercontent.com/5259870/106515568-c8827c00-64cd-11eb-9388-33cd01132dc6.png)

**Comment by josephdadams** [comment]
Yay!
