### ISSUE TITLE
Add support for StreamState of OBS

### ISSUE THREAD

**Issue by Gdmm97** [josephdadams/TallyArbiter#52]
Hi,
I used tallyArbiter in some recent streams and I would appreciate a Source for the current streaming-/
recordingState of OBS for the Speakers to reference.

Thanks
Gunnar

**Comment by josephdadams** [comment]
Implemented in https://github.com/josephdadams/TallyArbiter/commit/029092292b7968eee9c849626c0246adfeb42741
