### ISSUE TITLE
[Feature Request]: ATEM Aux Outputs as Sources

### ISSUE THREAD

**Issue by philglenny** [josephdadams/TallyArbiter#522]
### What feature would you like to see added to TallyArbiter?

As well as M/Es, it would be great to be able to select Auxes as sources into TA

**Comment by Smolinc** [comment]
+

**Comment by gavalierm** [comment]
I see this is possible for Ross switchers.. so maybe copy/paste the logic into ATEM module?

**Comment by zbynekdrlik** [comment]
+1

**Comment by Jocke4f** [comment]
The support for AUX busses for ATEM devices was added in https://github.com/josephdadams/TallyArbiter/pull/669.
