### ISSUE TITLE
[Bug]: OBS: Source in group and nested scenes unreliable

### ISSUE THREAD

**Issue by niklasberlin** [josephdadams/TallyArbiter#527]
### What happened?

Hey, first of all: great Software!

now for the Bug:

I have an element in OBS that I want to monitor and add a tally for it, when I use it in my regular scenes it works perfectly but when the element is inside a group element or within an embedded/nested scene TA does not work reliable

When the Element is inside a group I can toggle the visibility of the element or the visibility of the group while the scene with the group is in Preview, after toggling the visibility tally arbiter shows the correct state, but when the element is visible when I select the scene for preview, TA does not recognize this, same happens when I switch from preview to Program, TA does not recognize that the element is used inside a group. -> tally turns from green to off when I transition into the scene

When the Element is inside another scene and embedded/nested in the preview scene, the preview state works but when I toggle the visibility of the embedded scene, the tally stays green even when the source is no longer visible, in program nested/embedded scenes does not work at all.

this is probably caused by the messy way OBS has implemented the grouping/nested scene feature which is basically just another source that might contain other sources (yay recursion!)

I used OBS v28.1.2 with the websocket legacy plugin in version 4.9.1-compat and used the TA Backend and the Web-Client to check the tally status

I hope this is clear, otherwise I can record a short video to demonstrate this

### Version

3.0.4

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

### If applicable, What Listener Clients are You Using?

Web (Chrome)

**Comment by JTF4** [comment]
I think I'm getting that what your saying, but if you could record a video, that would be awesome. It would help us understand the issue a lot better.

**Comment by niklasberlin** [comment]
thanks for the fast reply

I created a quick video (without audio) where you can see what I do in OBS (I have four scenes, one where the source is used directly, one without any sources (to turn off the tally), one where the source is inside a group, and one where scene one is embedded), on top of the screen you can see a part of the Tally Arbiter Settings Window to display the current state of TA

video: https://youtu.be/-FjHHFBoVtA (not listed so only visible with this link)

**Comment by JTF4** [comment]
Yea. If you get a chance to try out the dev branch that would be awesome. 

In the meantime I'll have a look. I'm wondering if it's just a weird implementation of the legacy plugin. 

I've still got the older version of OBS installed on one of my machines and I'll see if it acts that way.

**Comment by niklasberlin** [comment]
I had a quick test with the dev branch, the Websocket v4 version worked better (nested scene got correctly recognized on Program), Groups still does not work, if the nesting has a depth of multiple layers I got a crash, I will test this further in the next days

with Websocket v5 it was more unreliable than before, but this might be a problem on my side (conflicting configs ,...), I will try it on a different computer with a clean install of OBS and TA and test again in the next days

**Comment by Jocke4f** [comment]
The problem is with websocket 5 and nested scenes. Nesting is not considered, the coce/logic is missing. It properly works with websockets 4.
