### ISSUE TITLE
Mac Install Weirdness

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#53]
Truly impressed with how well written this is. Amazingly easy to install and get running. Well done - Hat tip!

Having a problem getting the serve to run on startup on a Mac Mini under High Sierra. Code runs just fine running directly within Node.

Following the "Running as a Service" steps, the first issue I had was PM2 Start. I had to manually create the LaunchAgents folder, as it did not exist for the admin user account I was using. Once I created that folder, I had to run pm2 Start as sudo or I'd get an error that said permission denied when creating the file .pm2/pm2.log.

The second problem was that although pm2 startup seemed to work fine (creating the startup launch script), it never seemed to do anything. Tried as a basic user and using sudo, but no joy.

Any suggestions?

**Comment by josephdadams** [comment]
Thanks!

Can you get it to run at all with pm2?

`pm2 start index.js --name TallyArbiter`

If that works, then run `pm2 save` and reboot and let me know if that works.

**Comment by wrldtvlr** [comment]
Seems to be a permissions issue. It does start and run fine, but only if I preface the command with sudo. Same with pm2 save. Thought it might be because I had the TallyArbiter folder under Documents, but I moved it under Applications with no effect. The account I'm using has admin privileges, so I'm a bit stumped.

Not a big Mac person, but I'll see if I can figure out how Mac OS does permissions.

**Comment by wrldtvlr** [comment]
And it was a permissions issue. Had a mix of root and user permissions on the application and logs folders. Went and cleaned things up with chown and everything runs fine now, including restarting on power. Thanks for the help!
