### ISSUE TITLE
[Bug]: Programmed my M5StickC with arduino IDE and it's not showing tally

### ISSUE THREAD

**Issue by sempei13** [josephdadams/TallyArbiter#534]
### What happened?

I've use the latest Arduino IDE 2.0.3 to program my m5StickC and it programmed fine and I can go to its ip address and see the WIFI configuration, but that's all.  I've changed the tally arbiter ip address in the code before I programmed the stick and can go to that tally arbiter server on the same computer in the browser with the same first three octets.  I only have two screens, a booting screen (on the m5stickc) and the SSID and iP address screen.  That's it.

### Version

2.0.16

### Distribution

Desktop

### OS

MacOS

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by JTF4** [comment]
Is the device showing up in the listener client page?

**Comment by sempei13** [comment]
Not at all, but if I open a web page as a listener, those do show up.

**Comment by sempei13** [comment]
The web page listener shows, is what I mean.

**Comment by josephdadams** [comment]
the listener clients included in this repo for TA are not compatible with v2.0.16 of TA

**Comment by sempei13** [comment]
Fair enough.  Where is the M5StickC code that IS compatible with 2.0.16 OR where's the MacOS version of TA that's compatible with this version of the M5StickC?  Whichever is the latest, most stable release would be my preference.

**Comment by josephdadams** [comment]
TA v2.0.16 M5 listener: https://github.com/josephdadams/TallyArbiter-M5StickCListener
TA 3.0.4 release: https://github.com/josephdadams/TallyArbiter/releases/tag/v3.0.4
