### ISSUE TITLE
Listener keeping the same device

### ISSUE THREAD

**Issue by Kinderix** [josephdadams/TallyArbiter#536]
Is there a way that after I set on a listener the device to listen to it remains the same even after i disconnect the listener and reconnect it?

**Comment by hrueger** [comment]
What type of listener are you using?

**Comment by Kinderix** [comment]
ATOM Matrix

**Comment by Ja5-n** [comment]
It may be worth programming your router to give out a static IP address to each listener device. I’m doing that with the little WiFi network I use for the switchers, streamers, control systems and tally devices.

**Comment by josephdadams** [comment]
The listener clients are the ones that implement this, not the server. The. ATOM Matrix does not support this currently. If anyone wants to submit a PR for it, the code is very similar to the M5 which does support it

**Comment by Jocke4f** [comment]
Closing since this has already been added to the code in tallyarbiter-m5atom.ino. I however can't located the PR in the history that  fixed this but it works when I test it.
