### ISSUE TITLE
Device Source

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#54]
Sorry - one additional problem. Trying to link a listener to an ATEM Production 4K device source, the pulldown choices aren't readable. I was able to guess that the check was the one and only source I had defined, but had to manually enter the number.
![IMG_20210208_143523](https://user-images.githubusercontent.com/8150022/107300263-caed5480-6a3e-11eb-8adc-69345e7d440d.jpg)

**Comment by josephdadams** [comment]
ATEM source types don't populate the addresses in this list (yet).

As for the dropdown to choose the source, I'm wondering if there's a special character or something in the name of your ATEM source that's making it behave this way. Can you post your config.json file here?

**Comment by wrldtvlr** [comment]
Sure. I wonder if the Production 4K switchers do their name differently? I don't see that field populated below.

{
 "security": {
  "username_settings": "admin",
  "password_settings": "12345",
  "username_producer": "producer",
  "password_producer": "12345"
 },
 "sources": [
  {
   "sourceTypeId": "44b8bc4f",
   "enabled": true,
   "name": "",
   "reconnect": true,
   "data": {
    "ip": "192.168.1.202",
    "me_onair": [
     "1"
    ]
   },
   "id": "35271e08",
   "connected": true
  }
 ],
 "devices": [
  {
   "name": "5",
   "description": "Wide",
   "tslAddress": "0",
   "enabled": true,
   "id": "cee5ee97",
   "linkedPreview": false,
   "linkedProgram": false
  },
  {
   "name": "6",
   "description": "Dolly",
   "tslAddress": "",
   "enabled": true,
   "id": "9e100dab",
   "linkedPreview": false,
   "linkedProgram": false
  },
  {
   "name": "7",
   "description": "PTZL",
   "tslAddress": "",
   "enabled": true,
   "id": "f5c4071e",
   "linkedPreview": false,
   "linkedProgram": false
  },
  {
   "name": "8",
   "description": "PTZR",
   "tslAddress": "",
   "enabled": true,
   "id": "36bcec75",
   "linkedPreview": false,
   "linkedProgram": false
  },
  {
   "name": "1",
   "description": "Pana",
   "tslAddress": "",
   "enabled": true,
   "id": "ac7eb878",
   "linkedPreview": false,
   "linkedProgram": false
  }
 ],
 "device_sources": [
  {
   "deviceId": "cee5ee97",
   "sourceId": "35271e08",
   "address": "5",
   "id": "379b49b0"
  },
  {
   "deviceId": "9e100dab",
   "sourceId": "35271e08",
   "address": "6",
   "id": "49d6f400"
  },
  {
   "deviceId": "f5c4071e",
   "sourceId": "35271e08",
   "address": "7",
   "id": "3b3cb69d"
  },
  {
   "deviceId": "36bcec75",
   "sourceId": "35271e08",
   "address": "8",
   "id": "3a5f7d03"
  },
  {
   "deviceId": "ac7eb878",
   "sourceId": "35271e08",
   "address": "1",
   "id": "b1189554"
  }
 ],
 "device_actions": [],
 "tsl_clients": [],
 "tsl_clients_1secupdate": false,
 "cloud_destinations": [],
 "cloud_keys": []
}

**Comment by josephdadams** [comment]
Did you name it when setting it up? That field is whatever you want to put in it, but I don't really have any input checking on it, so it's possible to put special characters or things that would result in it not being saved or giving an error.

I usually just put 'atem'.

**Comment by wrldtvlr** [comment]
Must have not filled it in. Went back. deleted the source, then recreated it being sure to add a name and it works fine.
