### ISSUE TITLE
[Bug]: 3.0.4 constantly crashing

### ISSUE THREAD

**Issue by ChrisGlieber** [josephdadams/TallyArbiter#546]
### What happened?

TallyArbiter is constantly crashing after a while (after 2-5 Minutes). Running on Windows 10H22.

For Test Purposes I tried to connect over local Network (Ethernet) to OBS (other Machine) and later to ab BMD ATEM TV Studio Pro 4k. The ATEM was discovered automatically but didn't came online/available (OBS was not discovered). I also had the Problem that initially the default password (admin 12345) would'nt be accepted after first install in the Desktop app (wrong user or password). After several retries and switching to the webinterface (Firefox) it worked then and was saved somehow. Also had this behaviour in Version 2.0.16 - apart from the crashes.

Sorry, that i cannot provide any more useful information. I'm just a user, just signed up on github to Thank you for your work!

Chris

Machine has two Ethernet NICs serving two Networks with different IP Ranges. One of them static (no dhcp).

### Version

3.0.4 and 2.0.16

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### If applicable, What Listener Clients are You Using?

Web (Firefox)

### TallyArbiter configuration

```javascript
{
 "security": {
  "jwt_private_key": "c1IULRLOzJrgdXHmxmwZ5+UjfPBL3ywVSgml8VRJUoYi0lOgUY607SlilMQ18M3ykLo5jYWr4xx3uRD8LSu6Q6wwb3CEGTdA9zD9C5b1LlBl+pniRaIC0AbTI5M1mFU1eAYKmRYLdFZptovsGVE+X1DbOY5i69kVnqBoIoAHevDWMUf2960J8BYNVcseYmq7QLlrkUjDXPlUPjiyfT8LAIwpJQnHglnpFQuN1DkACrF6yiBnsJO42QsWgt5PNoKUVimCNXLcoBpzRk7puKPAuApvNCP+ECjHmWFYR9EQo9w4aJnWFx72CTXXz0MgztIz79U8yfbCpRm94xmamqiCSA=="
 },
 "users": [
  {
   "username": "producer",
   "password": "$2b$10$LJU.zFk/hmwndnYpn5jRZOO.heBBxUTfQVkmQzI/jxAnOxHt9yN0.",
   "roles": "producer"
  },
  {
   "username": "admin",
   "password": "$2b$10$Va58YD7lW0OJGTPJrtXJL.Cp7Py6CaCs5qK4tbPsv5jIWqQ238HES",
   "roles": "admin"
  }
 ],
 "cloud_destinations": [],
 "cloud_keys": [],
 "device_actions": [],
 "device_sources": [
  {
   "deviceId": "3d047c4b",
   "sourceIdx": "0",
   "address": "OFF AIR",
   "sourceId": "b86a9ee8",
   "id": "c4439b12",
   "rename": false
  }
 ],
 "devices": [
  {
   "name": "OnAir",
   "description": "Studio OnAir",
   "enabled": true,
   "id": "3d047c4b"
  },
  {
   "name": "Studio OFF Air",
   "description": "Schild",
   "linkedBusses": [
    "e393251c"
   ],
   "enabled": true,
   "id": "b0096680"
  },
  {
   "name": "CAM A",
   "description": "BMD Studio Cam 4k Pro",
   "enabled": true,
   "id": "16198786"
  }
 ],
 "sources": [
  {
   "data": {
    "ip": "10.0.0.137",
    "port": 4456,
    "password": "RVSwxY2aVpL0PE2m"
   },
   "name": "OBS Flurschild",
   "sourceTypeId": "4eb73542",
   "reconnect": true,
   "enabled": true,
   "id": "b86a9ee8",
   "max_reconnects": 5,
   "connected": false
  },
  {
   "data": {
    "ip": "10.0.0.137",
    "port": 4456,
    "password": "RVSwxY2aVpL0PE2m"
   },
   "name": "OBS Flur TV",
   "sourceTypeId": "4eb73542",
   "reconnect": true,
   "enabled": true,
   "id": "4d73317c",
   "max_reconnects": 5,
   "connected": false
  },
  {
   "name": "ATEM Television Studio Pro 4K",
   "data": {
    "addresses": [
     "10.0.0.92",
     "ATEM Television Studio Pro 4K._blackmagic._tcp.local"
    ],
    "ip": "10.0.0.92",
    "me_onair": [
     "1"
    ],
    "cut_bus_mode": "off"
   },
   "sourceTypeId": "44b8bc4f",
   "reconnect": true,
   "enabled": true,
   "id": "ba2acd8c",
   "max_reconnects": 5,
   "connected": false
  }
 ],
 "tsl_clients": [],
 "tsl_clients_1secupdate": false,
 "bus_options": [
  {
   "id": "e393251c",
   "label": "Preview",
   "type": "preview",
   "color": "#3fe481",
   "priority": 50
  },
  {
   "id": "334e4eda",
   "label": "Program",
   "type": "program",
   "color": "#e43f5a",
   "priority": 200
  },
  {
   "id": "12c8d699",
   "label": "Aux 1",
   "type": "aux",
   "color": "#0000FF",
   "priority": 100
  },
  {
   "id": "12c8d689",
   "label": "Aux 2",
   "type": "aux",
   "color": "#0000FF",
   "priority": 100
  }
 ],
 "externalAddress": "http://0.0.0.0:4455/#/tally",
 "remoteErrorReporting": false,
 "uuid": "2495f1c6"
}
```

**Comment by josephdadams** [comment]
what error messages are you getting to know it has crashed?

**Comment by ChrisGlieber** [comment]
Hello Adam,

sorry if my message has been too imprecise - I have too little experience in proper reporting here on Github.

As far as I can tell, there were no error messages, so no pop-up. But you probably mean a log file that I could have viewed? I'm sure it doesn't exist anymore. But I could certainly reproduce it again if that helps a bit?

The crashes were always like this:
The Electron app window suddenly disappears. If I then look in the system tray at the bottom of the Windows-taskbar, I still see the TallyArbiter icon for a short time until it also suddenly disappears. At the same time, the server was of course no longer accessible from the web frontend. The whole thing happened always after 1-4 minutes with version 3.0.4.

In the meantime there is a small update. I try to summarize:

A developer friend of mine helped me to program Arduino-based clients (D1 Mini-ESP8266+Neopixel LEDs) (with success!!! ; -) ). He ran TallyArbiter as a Linux App image on his notebook, as far as I understood. We had the following findings on Friday if I remember correctly (sorry if I'm speaking amateurish):

v3.0.4.: felt less crashy than on my machine, but unfortunately it did. BMD ATEM was automatically detected, but connection failed (always stayed red), also no connection with OBS from other machine, the ESP8266 client was not detected (but that could be because there were no data sources to assign to a device?).

v3.0.3: no crashes so far, ATEM was recognized, I could assign it as a source to my camera (device) and ESP8266 client was recognized. It was interesting that the ESP8266 client was only shown in TallyArbiter when a device with a source was created. Also, we once had the phenomenon that we deleted the ESP8266 client in TallyArbiter and after that this specific device (we had three of them) remained permanently disabled. As if it was stored in a kind of black list. We flashed another board and that was then immediately recognized. I'm not sure anymore what we did then - I think we deleted TallyArbiter completely, then that first client went on again too. So we stayed with the 3.0.3 and got the Arduino clients to work with it. Yay!

v2.0.16: no crash if I remember correctly, ATEM connection worked (but I think only manually), but the ESP8266 clients were not found even if I created my device and tried to assign a source.

Also: we had 2 or 3 times this strange phenomenon, that after a restart (or reinstallation?) of TallyArbiter we could not login with the default password (admin 12345). Then we got the error "wrong password or username".  I think we restarted or tried several times. At some point it worked. Unfortunately it was not reproducible and I’m not shure on which version since we constantly where switching. I think 3.0.4 and/or 3.0.3 

I'm afraid this doesn't help you much? Also because it is certainly incomplete from memory. If there is anything I can do to report better, feel free to let me know and I try to make it better. It will take me quite a few more days to get the server up and running on the machine it will eventually run on and also to set up the clients and sources, since I have to do that on the side.

Thanks again for your work, it’s great!

Chris

**Comment by hrueger** [comment]
Could you please start Tally Arbiter from the command line? It works like this:
1. Find the TallyArbiter folder (for me it is `C:\Users\Hannes\AppData\Local\Programs\TallyArbiter`, just replace `Hannes` with your username). There should be a `TallyArbiter.exe` file in there. 
2. In Windows Explorer in that folder, click in the bar where the breadcrumbs are:
![grafik](https://user-images.githubusercontent.com/18656830/218468986-1b8e6412-982c-4df2-89c9-bc589c02aff8.png)
3. Replace the path with `cmd` and press enter
4. Now in the console Window type `TallyArbiter.exe` and press enter. This starts the application and prints any logs directly to the terminal. When it crashes, you should see a crash report there!

The advantage of this over searching in log files is that we hopefully see a crash log there, even if it is not written to the disk.

**Comment by ChrisGlieber** [comment]
Thank you Hannes, I will do that as soon I'm on the machine and have the time.

best, Chris

**Comment by whizkidTRW** [comment]
Hannes, I'm trying to get TA 3.0.4 running for the first time on Windows as well and have the same issue. I just installed 3.0.4 via the windows installer and I get this:

```
Error: Cannot find module 'C:\Users\Todd\AppData\Local\Programs\tallyarbiter\resources\app.asar\node_modules\threadedclass\dist\child-process\threadedclass-worker.js'
    at o ([worker eval]:1:13868)
    at Function.t._findPath ([worker eval]:1:11173)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at i ([worker eval]:1:132)
    at [worker eval]:1:306
    at Object.1.asar-node ([worker eval]:1:640)
(node:13216) UnhandledPromiseRejectionWarning: Timeout when trying to restart
(node:13216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 367)
```

**Comment by hrueger** [comment]
Strange, does not happen for me 🤷‍♂️
Unfortunately, due to university I don't have time to work on this currently and in the near future.

**Comment by chanx** [comment]
@whizkidTRW can you try this build? https://github.com/chanx/TallyArbiter on my test laptop 3.0.4 is crashing too, but for 2.0.16 is not. But with built 3.0.5 from my repo is okay. No crash and can connect to bmd atem tv hd.

For error with password, when that happened maybe you can try exit the tally arbiter then relaunch it. For exit you have to do it from system tray, not just close the window, because when you click x it is minimized to system tray.
