### ISSUE TITLE
Matrix Listeners Not Detected

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#55]
Any suggestions on how to troubleshoot a couple of M5 Atom Matrix listeners not being detected? I've programmed 4. Two show up in the listeners list, two do not. They all have the same client code and were all purchased new. They all have IP addresses assigned. The two that aren't showing up do not have any entries in the TallyArbiter log window.

I have a couple of additional Matrixes I will try today. They only thing I can think of is that two of the original 4 might be defective.

**Comment by BenniKa** [comment]
have you tried completely erasing them for example via m5 burner and then reflashing them? that worked for me, because somehow the given deviceID was wrong and could not be detected by the server.

**Comment by wrldtvlr** [comment]
Interesting. On my way to system. If these alternate Matrixes don't get identified, I'll try erasing.

**Comment by wrldtvlr** [comment]
OK, the two new M5 Atom Matrixes were not recognized either. It's not entirely clear to me what M5 Burner does for me though as I do not use UIFlow, just the Arduino IDE. As far as I can tell, that is working OK as I can load and execute sketches with no problem.

**Comment by wrldtvlr** [comment]
Sigh. I wish I could say what I did, but after hours of trying different things, including installing the Arduino IDE fresh on a Mac and then having to run down a python problem with Big Sur, I am successfully running the Matrix clients. I suspect I have a library issue on my main Windows machine. At some point I'll reinstall there, but for now I'm happy to close this.
