### ISSUE TITLE
Linux installation not working

### ISSUE THREAD

**Issue by under-score** [josephdadams/TallyArbiter#560]
OSX installation works but Debian doesn't, see npm debug log

[npm-debug.log](https://github.com/josephdadams/TallyArbiter/files/11303169/npm-debug.log)

**Comment by josephdadams** [comment]
The debug log literally says it is an error with npm itself and not tally arbiter

**Comment by under-score** [comment]
thank you - I agree it was a npm thing where [neither early nor late](https://nodejs.org/en/download/releases) versions are working. In the end npm 8.19.4 and node 16.20.0 installed TallyArbiter without error notice.
