### ISSUE TITLE
[Bug]: Tally Arbiter M5 Stick-C Listener could not be downloaded

### ISSUE THREAD

**Issue by mmattausch** [josephdadams/TallyArbiter#561]
### What happened?

was trying to do an upgrade to an older Tally installation and its M5Sticks. While following youre guide "From here, scroll down to the "Artifacts" section and click on "TallyArbiter-Listener-M5StickC" it is impossible to download the binaries, because it states "expired, you can no longer download it.

https://github.com/josephdadams/TallyArbiter/actions/workflows/build-listener-clients.yaml

seems the last run is +4 mon old and so it expired somehow

### Version

current

### Distribution

Source

### OS

Linux

**Comment by Julusian** [comment]
I found this too.

Perhaps they could be attached to a release instead? It might make more sense to have a repository containing just the listeners if doing that though

**Comment by josephdadams** [comment]
The latest release has new artifacts. I will see if we can start attaching them to the releases.
