### ISSUE TITLE
First Production Went Well!

### ISSUE THREAD

**Issue by wrldtvlr** [josephdadams/TallyArbiter#57]
Didn't find a discord group or other discussion platform that seemed appropriate, so I'll leave this here...

We did our first live production today using TallyArbiter polling an ATEM Production 4K switcher, 5 cameras along with four Atom Matrix listeners and it went very well. Everything worked just as it should. Running the server code on the same Mac Mini as our Wirecast instance. Thinking I might move the TallyArbiter server to a dedicated Raspberry Pi to avoid any possible problems in the future, but don't have any justification for doing so.

**Comment by wrldtvlr** [comment]
And since this isn't an issue, I'll close it!

**Comment by josephdadams** [comment]
That's awesome! Thanks for letting me know!
