### ISSUE TITLE
[Bug]: GPO Listener No Connection to Server

### ISSUE THREAD

**Issue by ruebyi** [josephdadams/TallyArbiter#572]
### What happened?

The GPO Listener does not connect to server.
It gets a client ID, but does not Show up as client and does not react to changing tally status.

I‘m using the lates GPO Repository

### Version

2.0.16

### Distribution

Desktop

### OS

MacOS

### If applicable, What Listener Clients are You Using?

GPI

**Comment by hrueger** [comment]
Hi @ruebyi,
are you sure you're not using a listener client made for v3 with TA v2?

**Comment by ruebyi** [comment]
Oh, how can I see wich version I have? 
i used ist stable version and the listener code that is here in the repository

**Comment by hrueger** [comment]
In TA you can go to "About" to find the version.
As far as I know, listener clients in this repository are for v3 only. Listener clients for v2 and earlier were in separate repositories: https://github.com/josephdadams/TallyArbiter-GPOListener

**Comment by ruebyi** [comment]
thank you!
