### ISSUE TITLE
Problems with Device Action TCP

### ISSUE THREAD

**Issue by RaulDuke77** [josephdadams/TallyArbiter#59]
Hello,

i have a problem with the Device Action TCP.

System: Apple MBP MacOS 10.15.7
Software: OBS, TallyArbiter, Bitfocus Companion, PacketSender

The Preview, Programm Part works fine.
When i configure a TCP Action Device Action to send a command to Companion, TallyArbiter connects to Companion but does not send the command and does not disconnect.
With every switch, TallyArbiter connects on a new Port, but never disconnects.
When i close TallyArbiter all  Ports in Companion are closed immediately.
When i send a TCP command from PacketSender to Companion everything works fine.
When i send a TCP Device Action from TallyArbiter to PacketSender, it receives the Command but also does not disconnect.

Also i cannot choose any listener clients in companion, i don't know if this is part of the same problem.

Thank you for this program and your help.

<img width="463" alt="TCP_Configuration" src="https://user-images.githubusercontent.com/48443055/108763450-acfd1500-7551-11eb-8d4b-1a2299ec987b.png">

<img width="463" alt="Client_Connected" src="https://user-images.githubusercontent.com/48443055/108763474-b2f2f600-7551-11eb-9fdb-4aa9fadcc12d.png">

<img width="891" alt="Recieve in Packet Sender" src="https://user-images.githubusercontent.com/48443055/108763516-bd14f480-7551-11eb-9ae2-018b4d2a3622.png">

<img width="556" alt="Client_Disconnected" src="https://user-images.githubusercontent.com/48443055/108763551-c605c600-7551-11eb-8ef9-74c823eaccc9.png">

**Comment by josephdadams** [comment]
Can you try this with the latest version and see if it is any better?

**Comment by RaulDuke77** [comment]
Hello Joseph,

thanks for your effort.
Yes it is better, it works as expected.
With every TCP Action a new Port is opening and closing, i don't know if that can be a problem.
But it is unlikely to run out of Ports, right.

Now i can trigger multiple Panasonic PTZ Camera presets with the Preview Bus of my ATEM 4M/E
Thank you very much.


![Companion](https://user-images.githubusercontent.com/48443055/111455768-7eb8c280-8716-11eb-83b7-ec04e9ec9863.jpg)
