### ISSUE TITLE
[Bug]: Wrong Architecture

### ISSUE THREAD

**Issue by whizkidTRW** [josephdadams/TallyArbiter#608]
### What happened?

On windows 11, I cloned the repo and when I did the 'npm install' it errored out with `unsupported platform for fsevents@2.3.3`.

### Version

3.0.4

### Distribution

Source

### OS

Windows

### TallyArbiter configuration

```javascript
N/A - no config yet, won't install!
```

### Relevant log output

```shell
C:\tallyarbiter>npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Todd\AppData\Roaming\npm-cache\_logs\2023-11-13T21_20_19_033Z-debug.log
```

**Comment by hrueger** [comment]
> This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

make sure to use a more recent version of npm. If that does not fix the issue, most of the dependencies of this project could probably be updated ;-) Unfortunately, due to university I don't have time to work on this currently and in the near future.

**Comment by whizkidTRW** [comment]
No worries! I noticed that I was running nodeJS v14 after I posted this. I
didn't realize it was so horribly out of date! After upgrading to v20, it's
working much better now, though I'm still not getting tally from my ATEM
Mini, but I'm still working on it.

Thanks!

Todd Witten
***@***.***

**Comment by hrueger** [comment]
Can we close this then?

**Comment by whizkidTRW** [comment]
Yes, absolutely. Thanks!

Todd Witten
***@***.***
