### ISSUE TITLE
Unable to add Source Carbonite

### ISSUE THREAD

**Issue by DeeJayMX** [josephdadams/TallyArbiter#61]
When I'm trying to add carbonite and click SAVE, nothing continue.
the pop-up stay open...

**Comment by DeeJayMX** [comment]
I'm on Windows by the way...

**Comment by DeeJayMX** [comment]
I tried on Chrome and Edge, sorry for the multi-posting
And I'm using the last version from git

**Comment by josephdadams** [comment]
I pushed a fix for this within the last half hour, so please try again.

**Comment by josephdadams** [comment]
Did the latest help?
