### ISSUE TITLE
[Bug]: ATEM Constellation 2 M/E not connecting

### ISSUE THREAD

**Issue by farmsm77** [josephdadams/TallyArbiter#619]
### What happened?

Using version 3.04, the ATEM Constellation 2 M/E does not connect. From the same PC, I can ping it.

### Version

3.04

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### If applicable, What Listener Clients are You Using?

M5 Stick

**Comment by Jocke4f** [comment]
Does it work with 3.0.5? There is a fix regarding ATEM handling added to 3.0.5.

**Comment by farmsm77** [comment]
I see source code for 3.05 but no .exe installer file. Forgive my ignorance, please, but I haven't installed from source code before.

**Comment by Jocke4f** [comment]
Can you test with 3.0.6? This release includes the installers: https://github.com/josephdadams/TallyArbiter/releases/tag/v3.0.6

**Comment by Jocke4f** [comment]
Have you hade time to verify this? I have tested v3.0.7 with both ATEM Television Studio and ATEM ATEM Mini Extreme ISO without any issue when using the IP address for the connected ATEM devices.

**Comment by farmsm77** [comment]
Hi Joakim,

I have tested it and it appears to be working. I had some trouble with the listener from my M5StickC but I think I was able to resolve that by uploading a newer version of the sketch to a test M5 that I had lying around.

I am hoping to apply my tests to the system this weekend, so I will let you know how that goes.

Cheers,
Steve Farmer
Open Door Baptist Church
Rochester, NY

**Comment by Jocke4f** [comment]
Hi Steve,

Any conclusion?

**Comment by farmsm77** [comment]
Hi Joakim,

Thanks for contacting me. It’s been a frustrating exercise. to be honest. I thought I had things working, but once I connected everything back up, the M5stickC listeners would not populate in Tally Arbiter even though the display on the units was showing them as being connected to the Tally Arbiter server. I thought there may have been some issues with the firewall on the Windows PC, but there were none that I could find.

I then went back to the drawing board and tried some older M5stickc setups and tried installing them form Arduino updating libraries; etc., in the process. Nothing has worked, thus far.

I just purchased some M5stickC Plus2 units for another project I am doing, thinking I could get something going with them, but I do not even see a project for these units and Tally Arbiter. I am not a programmer so starting one of these is not something I feel I can do.

If you have any thoughts on what I might need to do, I would love to hear them. In the meantime, I am going to keep trying to get them working. My camera ops are starting to complain so I need to get these working soon.

Cheers,
Steve Farmer

**Comment by Jocke4f** [comment]
Hi Steve,

2.x vs 3.x
I assume that you are aware of that the api between TA and the client listeners is not the same for 2.x and 3.x. So you both TA and the client listeners must be either 2.x or 3.x.

m5stick
The TA m5stick listener is either the normal or the plus version. I don't know if the Plus2 is backward compatible with Plus.

So what listener versions are you using?
Is the M5StickC, M5StickCPlus or M5StickCPlus2?

**Comment by farmsm77** [comment]
Hi Joakim,

I figured that there was a client change with going from TA 2.x to 3.x. I have tried both the old and new sketches on both the M5stickC and the M5stickC Plus2. I would have liked to get some Plus units, but they appear to be in short supply.

My intention is to continue to use the M5sickC with TA 3.x, but, so far, no luck. I’ll keep working to get it, but I am feeling stuck right now.
 
Cheers,
Steve Farmer

**Comment by Jocke4f** [comment]
Do you configure the Tally Arbiter Server address in the sketch?

**Comment by farmsm77** [comment]
Depends on the sketch.

There is one I found which enables the M5 to have a local WiFi server where I then have to connect and change it from a server to a client. Then it gets a DHCP address and I can enter that address into TA. This seemed to work once but when I moved from my test site to my production suite and reflashed the unit with the new parameters, the units would not switch from server to client no matter how many times I reprogrammed them.

Another sketch needed fixed IP’s in the config so I programmed each one with an address and launched TA. The M5’s looked like they were connected but TA was not showing any listeners.

I am going to spend some time today trying again. I will let you know how it goes.

Cheers,
Steve Farmer
Open Door Baptist Church

**Comment by Jocke4f** [comment]
I have not tried the scenario when you have the M5 configured for one WiFi network and then move it to a different WiFi network. I had the scenario that it got stuck search for the "old" WiFi network one time so I always avoid this. I always used the Erase WiFi config option on the Info page for the WiFiManager

What I have noticed is that when I on a M5 unit update the TA ip address, that is configured and connected to a network, I must restart the M5 to connect to the correct IP address.

**Comment by farmsm77** [comment]
Thanks for the tip, I’ll look into that.

**Comment by farmsm77** [comment]
So, I was able to connect to my home network with each of the M5 units and test them in TA successfully. At home, the units picked up a DHCP address from my WiFi. All good, right?Took the units to church, entered in the TA server address in Arduino and uploaded the new config. Now the M5 units show a configuration timeout. It does not appear that they are connecting to the WiFi at church.Not sure how to config these for a static address now that those parameters are no longer in the section for user config.Cheers,Steve Farmer On Jan 27, 2024, at 8:08 AM, Steve Farmer ***@***.***> wrote:﻿Thanks for the tip, I’ll look into that.On Jan 27, 2024, at 8:04 AM, Joakim Forsberg ***@***.***> wrote:I have not tried the scenario when you have the M5 configured for one WiFi network and then move it to a different WiFi network. I had the scenario that it got stuck search for the "old" WiFi network one time so I always avoid this. I always used the Erase WiFi config option on the Info page for the WiFiManagerWhat I have noticed is that when I on a M5 unit update the TA ip address, that is configured and connected to a network, I must restart the M5 to connect to the correct IP address.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Jocke4f** [comment]
It sounds like the device is searching for the home WiFi Network since old WiFi network settings are still present. Does it work to press the M5 button for 5 seconds to trigger an erase of WiFi settings and a device restart. This should trigger a fresh startup of the device so that the WiFi can be configured via the m5stickC-XXXXXX network.

**Comment by farmsm77** [comment]
Yep, that was it, exactly. I realized right after I sent that email.

Thanks for the help, everything is working now!

One thing I am seeing in TA is that there is a TSL client listed but it cannot be deleted. Other than that, everything is good.

Cheers,
Steve Farmer
