### ISSUE TITLE
AUX as an addition to Programm and Preview

### ISSUE THREAD

**Issue by ruebyi** [josephdadams/TallyArbiter#63]
Hi, 

we ran into a "problem" on sunday when we were Streaming on an ATEM Television Studio HD.

We sent out a stream on ME1 and we send out an Aux Signal to a Beamer in the Curch.

It would be so helpful if the tallys could also send out a Message when the Camera is on Aux... Lets say in White? (That's the color of the Aux Buttons on the ATEM Television Studio HD).

Thank you very much for your great work!

**Comment by josephdadams** [comment]
Great idea! I'm definitely considering adding an aux bus.

**Comment by MrLazerface** [comment]
+1 for this request. The new tally implementation in Barco Event Master products has support for aux bus tally, and internally they use yellow as a color to indicate a source is live on an aux bus.

**Comment by Haavard15** [comment]
+1 on this

**Comment by Jocke4f** [comment]
The support for AUX busses for ATEM devices was added in https://github.com/josephdadams/TallyArbiter/pull/669.
