### ISSUE TITLE
multi-interface listening

### ISSUE THREAD

**Issue by joshua-wyatt** [josephdadams/TallyArbiter#66]
I'd like to run Tally Arbiter on a PC that's connected to more than one network -- eg. I have two network adapters.  Is there a way to specify which interface Tally Arbiter should listen on (for instance, when creating a TSL source for a Carbonite)?  Or, to have it listen on ALL interfaces?

**Comment by josephdadams** [comment]
The default behavior is that it will listen on all interfaces. TA does not specifically bind to one interface. So if you set up a TSL source and listen on port 9800, for example, any traffic from any network card that comes in on that port 9800 will flow to TA for processing. This is sometimes referenced as listening to 0.0.0.0.

Is it a security concern that you want to limit it to one interface?

**Comment by joshua-wyatt** [comment]
Thanks for the information.  Listening on all interfaces is preferred, and there's no security concern -- I just haven't been able to make it work yet (receiving TSL from my Carbonites) so thought it may have been listening on eth0 only.  I'll do some digging with packet capture tools to make sure the TSL traffic is actually making it to the machine running TA.

**Comment by josephdadams** [comment]
Feel free to email me if you need help. I use carbonites daily with TA.

**Comment by josephdadams** [comment]
I will close this since TA runs on multiple interfaces by default.
