### ISSUE TITLE
[Bug]: GPO-Listener Invert Output

### ISSUE THREAD

**Issue by DJLWegas** [josephdadams/TallyArbiter#661]
### What happened?

If you invert the output in the config file and then flash a listener, the flash works but it does not end in the last state. It ends in the oposite state. If the source has Tally, the output stays LOW (should be HIGH) at the end of the flash and if the source has no Tally, the output stays HIGH (should be LOW) at the end of the flash.

### Version

3.0.8

### Distribution

Desktop

### OS

Windows

### If applicable, What Listener Clients are You Using?

GPI

**Comment by Jocke4f** [comment]
Do you have the possibility to test the fix on  [Jocke4f:fix_661_gpo_invert](https://github.com/Jocke4f/TallyArbiter/tree/fix_661_gpo_invert)? At the moment don't I have anything to test with.

**Comment by Jocke4f** [comment]
Fix verified with a RPI 4 with single led. This has now been solved on master when https://github.com/josephdadams/TallyArbiter/pull/675 was merged.
