### ISSUE TITLE
Startup with PM2

### ISSUE THREAD

**Issue by jerriley** [josephdadams/TallyArbiter#68]
Running Tally Arbiter fine with PM2. Followed all the instructions for having it run on startup. It seems like it wants to, but it's running into a problem. If I reboot, then run pm2 list, I get this. Notice the version says N/A.

<img width="836" alt="Screen Shot 2021-03-14 at 2 58 22 PM" src="https://user-images.githubusercontent.com/35228159/111085710-c1d82300-84d5-11eb-9307-f764add5866c.png">

If I run pm2 logs, then I get the following repeating over and over:

<img width="712" alt="Screen Shot 2021-03-14 at 2 43 19 PM" src="https://user-images.githubusercontent.com/35228159/111085739-db796a80-84d5-11eb-84a2-539ad44d229f.png">

Any ideas?

**Comment by josephdadams** [comment]
This looks like MacOS. Can you try running it with `sudo`?

**Comment by jerriley** [comment]
I can run it fine with pm2. It's just after restarting the computer that I get the errors shown above. Here's it running fine:

<img width="842" alt="Screen Shot 2021-03-14 at 5 23 08 PM" src="https://user-images.githubusercontent.com/35228159/111089660-0bcb0400-84ea-11eb-9c7f-13e487bdfdd2.png">

**Comment by josephdadams** [comment]
Right. But I want to know if it works on reboot if you set it up with sudo.

**Comment by jerriley** [comment]
I ran "sudo pm2 save" and "sudo pm2 startup". Rebooted and it's giving me the same errors.

**Comment by josephdadams** [comment]
They run as separate processes so be sure to clear out the regular pm2 and save that. Then run sudo pm2 . It’s a file access permission error that I’m seeing.

pm2 kill
pm2 save

sudo pm2 start index.js
sudo pm2 startup
sudo pm2 save

reboot

sudo pm2 list

**Comment by jerriley** [comment]
I executed those commands (had to --force on pm2 save since there were no active processes). Running as root. However same error.

<img width="799" alt="Screen Shot 2021-03-14 at 5 45 50 PM" src="https://user-images.githubusercontent.com/35228159/111090520-3bc7d680-84ed-11eb-9b0f-2ac31e9cfb0a.png">

**Comment by josephdadams** [comment]
Make sure you don't have any odd permissions set in your ~/Documents/tallyarbiter/ folder.

I haven't seen or experienced this error before so I am just trying to give you troubleshooting tips to resolve the permissions issue.

**Comment by jerriley** [comment]
Yep checked the parent folders up the line and all have read/write permissions. I found a workaround I'm happy enough with. Just made a  script which does "pm2 resurrect" and running it on startup. Does the same thing and actually works.

**Comment by josephdadams** [comment]
Good fix!
