### ISSUE TITLE
[Bug]: error install Pimoroni Blinkt! Listener

### ISSUE THREAD

**Issue by peterv0101** [josephdadams/TallyArbiter#681]
### What happened?

A bug happened! pi@rpi:~ $ sudo pip3 install zeroconfig
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement zeroconfig
ERROR: No matching distribution found for zeroconfig

### Version

Raspberry PI OS (Legacy, 32-bit) Releasw datum: 2024-03-12

### Distribution

Desktop

### OS

Windows

### If applicable, What Listener Clients are You Using?

Blinkt

**Comment by josephdadams** [comment]
That’s because it’s zeroconf not zeroconfig
