### ISSUE TITLE
Blackmagic GPI/Tally Interface

### ISSUE THREAD

**Issue by Keksstar** [josephdadams/TallyArbiter#694]
Hi!

Is there a way to use TallyArbiter with the BMD GPI Tally Interface? If not, how can I get GPO out of TA? (Relay Board?)

Thanks!

**Comment by josephdadams** [comment]
Most people use the GPO listener client on an rPi. If you need contact closure instead, use the relay client.

**Comment by josephdadams** [comment]
We would have to emulate an ATEM to use the BMD interface.
