### ISSUE TITLE
[Bug]: Interface slowdown after extensive usage

### ISSUE THREAD

**Issue by kolele** [josephdadams/TallyArbiter#695]
### What happened?

After running for about 7 days interface will start slowing up.

As each day passes, it takes longer to load tabs like "Logs" under settings. Similarily, "Config" tab will take alot to load.

Eventually after 30ish days of uptime, web interface will not even load.

After restarting application, everything reverts to normal.

I use three Newtek vision mixers which i monitor for tally states simultaniously. 

Has anyone had similar experience?

### Version

3.0.10

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by josephdadams** [comment]
Yes I see this too. I think it’s the massive amount of tally data coming in and trying to be loaded.

**Comment by kolele** [comment]
Is there perhaps a way to turn off logging? That would make this applications operable 24/7 unattended.

**Comment by josephdadams** [comment]
Yep it’s open source so have at it

**Comment by kolele** [comment]
Ok fair enough.

Thanks!
