### ISSUE TITLE
[Bug]: Access Point not showing

### ISSUE THREAD

**Issue by lfsantana** [josephdadams/TallyArbiter#697]
### What happened?

A bug happened!
I installed the McStickC Listener client on an M5CstickCPlus2 board. After starting it with a power source an internal green LED lights up but the AP never shows up and I can't connect to the server. 

### Version

3.0.10

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### If applicable, What Listener Clients are You Using?

M5 Stick

### TallyArbiter configuration

```javascript
{
  "security": {
    "jwt_private_key": "MwL7poczKcKEDHEh2Et/Ah131Q9o5wsWsoHOD2chjSurmaKgjHjHs1LTUuVme81TNC1XKLmZd3pcF1f4pLLfBS+C2+nZtm/rrC8unKZ8Jkgm/x9ymYzuvk2diLyS1o67M9nJbGVDCWCZIrJHrntVhfVoTSEvPPpkjjPMjA97ZC1VH80mPDXaMSj/0g2VjUKao5k6i8dmcmgpc/vAkjjZKrbnbPBg8DmByS0VA0BqPBTkpuWhqYXo0LUb5Kri0+zquZ7plMYDp8pvVC9oiX7Al6SNYUICa38VrfWLvSXM6Z5r4u1vOEdQt4u8CTz2dANq9AhGRLFS8C4WUAFpQCL93w=="
  },
  "users": [
    {
      "username": "producer",
      "password": "$2a$10$HQqqKKL.Ih65tt0AsLhrbulaeB/9fzRwgsNiwbc0i2ifoLU2YOOLe",
      "roles": "producer"
    },
    {
      "username": "admin",
      "password": "$2a$10$4XzspucqtFZGtGW0/uRVzeSxaJMeAKmvjRdRLwSOhHonsaWEtpAze",
      "roles": "admin"
    }
  ],
  "cloud_destinations": [],
  "cloud_keys": [],
  "device_actions": [],
  "device_sources": [],
  "devices": [],
  "sources": [],
  "tsl_clients": [],
  "tsl_clients_1secupdate": true,
  "bus_options": [
    {
      "id": "e393251c",
      "label": "Preview",
      "type": "preview",
      "color": "#3fe481",
      "priority": 50
    },
    {
      "id": "334e4eda",
      "label": "Program",
      "type": "program",
      "color": "#e43f5a",
      "priority": 200
    },
    {
      "id": "12c8d699",
      "label": "Aux 1",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    },
    {
      "id": "12c8d689",
      "label": "Aux 2",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    }
  ],
  "externalAddress": "http://0.0.0.0:4455/#/tally",
  "remoteErrorReporting": false,
  "uuid": "e255a584"
}
```

**Comment by Jocke4f** [comment]
Is the used image built for the board M5StickC-Plus2 or is it the pre-built version for M5StickC?

By selecting the appropriate board type Arduino IDE builds for the hardware. The m5stick board types are:
- M5StickC
- M5StickC-Plus
- M5StickC-Plus2
The built image is specific to the board type.

The pre-built version is **only** for M5StickC.

**Comment by lfsantana** [comment]
I’m using the Arduino IDE with an M5StickC-Plus2 with the listener build
from the Tally Arbiter git-hub. After I upload the sketch the screen goes
black. I plug it to a power source and press de left button. An internal
green LED lights up, and that’s about it. I can’t see an access point or
connect it to my network.

Regards,

**Comment by Jocke4f** [comment]
Are you building for the board type M5StickC-Plus2?

![image](https://github.com/josephdadams/TallyArbiter/assets/39942694/2a1120a7-8ffb-4017-9156-203453b08157)

The scenario with green led after boot up on a sounds very much how it looks if the build was made for the board type M5StickC and uploaded to a M5STickC-Plus2 hardware.

**Comment by lfsantana** [comment]
[image: image.png]

**Comment by Jocke4f** [comment]
Sorry, can't read your replay

**Comment by lfsantana** [comment]
I fixed it!
Since you said it was working as the M5StickC,
I basically avoided including al the other boards, and removed some of the
code for the other models. It basically just works for the M5StickCPlus2
and It's woking fine.
Thanks,

**Comment by Jocke4f** [comment]
It is **one** common sketch for all three board types, even though the three hardware boards are different. The different boards are handled with the Arduino IDE preprocessor flags:
- ARDUINO_m5stack_stickc
- ARDUINO_m5stack_stickc_plus
- ARDUINO_m5stack_stickc_plus2

It is crucial to setup Arduino IDE with the correct board type before compiling since Arduino IDE will the use specific preprocessor flag for the selected board type. You can only build for one board type at a time since the image will be board type specific.
