### ISSUE TITLE
[Feature Request]: Control external LED

### ISSUE THREAD

**Issue by kgfox1** [josephdadams/TallyArbiter#699]
### What feature would you like to see added to TallyArbiter?

I am attempting to wire a NeoPixel Jewel 7 to a M5Stick C Plus.  I noticed in the code for the listener that it should send data to external (either G26 or G36).  I am connecting the GND, 5V Out, and G26 to the Jewel, but there is no life in the LED.  What am I missing?

**Comment by Jocke4f** [comment]
To enable usage of the external pins you need to change
#define TALLY_EXTRA_OUTPUT false
to
#define TALLY_EXTRA_OUTPUT true
before you compile the sketch.
