### ISSUE TITLE
font size in Tally View

### ISSUE THREAD

**Issue by juergen-miessmer** [josephdadams/TallyArbiter#70]
Hello Joseph Adams,
thanks a lot for your work. Great piece of software.

Is there a posibility to change the font size of Name and/or Description shown in Tally View?
Also a posibility to get rid of the "Show Chat" button and the menu?

I would like to use Tally View as a big "ON AIR"-sign next to the door of our Stage.

Thanks
Juergen

**Comment by josephdadams** [comment]
You can modify the custom.css and override any of the CSS that you wish. Just target `#divTally` with whatever CSS you want.

To turn off the chat you could add a CSS rule to set `#divMessages` to `display:none;` or you could just append `?chat=false` to the tally viewer URL and it will turn off.

**Comment by juergen-miessmer** [comment]
Thanks for reply.

Changing  font-size: 5vmin  to  40vmin  at  .tallyDeviceTitle  in  custom.css  did the job.

127.0.0.1:4455/tally?chat=false  has no effect, chat is still there.
#divMessages { display: none; }  in cumstom.css has also no effect.
#divMessagesDiv { display: none; }  has effect, but I additionaly need to comment out the button in tally.html

Is there a parameter to select a device by URL ?

**Comment by josephdadams** [comment]
/tally?deviceid=9fe2efd9a (replace 9fe2efd9a with your actual DeviceId)
