### ISSUE TITLE
Is Tally Arbiter working with ATEM Mini Extreme ISO ? No tally status

### ISSUE THREAD

**Issue by Jee10** [josephdadams/TallyArbiter#71]
Hello !!

Thank you for your incredible work, finally there's a simple way to manage tally !

Except in my case :D I have a ATEM Mini Extreme ISO, I'm trying to use TallyArbiter with but it doesn't work properly...
I have a connection with the ATEM (it's in green), but no communications when I change the preview/program status of a camera.

I think I've well configured the cam, sources, but no tally communication, the green and red status only work in test mode.

Is somebody have any help or idea ? Or maybe it's not simply compatible with this ATEM ??

Thank you,

Jérôme

**Comment by josephdadams** [comment]
It should be compatible. I desire it to be compatible.

Send me some screenshots of your ATEM source configuration, and/or include your config.json file.

**Comment by josephdadams** [comment]
@Jee10

**Comment by Jee10** [comment]
Hi Joseph,

Thank your for your reply.

Here is screenshots and config.json file content :

<img width="1367" alt="Capture d’écran 2021-03-26 à 13 20 08" src="https://user-images.githubusercontent.com/81281175/112631096-bfab8800-8e36-11eb-9562-7598cb4e8154.png">

Content of config.json :
-------------------

{
 "security": {
  "username_settings": "admin",
  "password_settings": "12345",
  "username_producer": "producer",
  "password_producer": "12345"
 },
 "sources": [
  {
   "sourceTypeId": "44b8bc4f",
   "enabled": true,
   "name": "192.168.1.94",
   "reconnect": true,
   "data": {
    "ip": "192.168.1.94",
    "me_onair": [
     "1",
     "2",
     "3",
     "4",
     "5",
     "6"
    ]
   },
   "id": "d8f62ea3",
   "connected": true
  }
 ],
 "devices": [
  {
   "name": "CAM 1",
   "description": "Camera 1",
   "tslAddress": "0",
   "enabled": true,
   "id": "40e95dc9",
   "linkedPreview": true,
   "linkedProgram": true
  }
 ],
 "device_sources": [
  {
   "deviceId": "40e95dc9",
   "sourceId": "d8f62ea3",
   "address": "1",
   "id": "af91c3a4"
  }
 ],
 "device_actions": [],
 "tsl_clients": [],
 "tsl_clients_1secupdate": false,
 "cloud_destinations": [],
 "cloud_keys": []
}

---------------------

**Comment by Greiffenberg** [comment]
The issue is at line 2539:
else if (path[h].indexOf('video.ME') > -1) {

The mini is sending "video.mixEffects"

I only have a mini, not sure whether the other Atems do as well. Otherwise be glad to make a pull request

**Comment by josephdadams** [comment]
A PR would be great. Maybe have it check for both .ME and .mixEffects?

**Comment by josephdadams** [comment]
@Jee10 go try the latest code which reflects this PR

**Comment by Jee10** [comment]
Hi Joseph,

Thank you for all, it working well since the update.

That’s a really good job !! Congrats and thank you again for that useful system.

Take care !

Jérôme
