### ISSUE TITLE
Pimoroni LEDs blink in a random manner 

### ISSUE THREAD

**Issue by federmpi** [josephdadams/TallyArbiter#73]
Hi Joseph,

Thank you very much for your Tally Arbiter, it's impressive!

Unfortunately I am seeing some unexpected behaviour when I plug in my Raspberry Pi 3B and launch the **Internal Test Mode** in the NodeJS server. I was expecting to see the colour red (programme mode), green (preview mode) and yellow (programme + preview mode), but what I see is that the LEDs blink in a random manner with random colours.

I have tested just the hardware of the Raspberry PI by creating a minimal test case with only the **doBlink(r, g, b)** function and without the interaction with the NodeJS server and it works as expected.

In order to further debug the problem I have added in the tallyarbiter-pimoroni-blinkt-listener.py script in the **processTallyData()** function a statement to print each device_state and in the **evaluateMode()** function a print statement to see the values of the **mode_program** and **mode_preview** variables and the expected value of the **doBlink(r, g, b)** function.

Below you can see the output of the modified tallyarbiter-pimoroni-blinkt-listener.py. Do you know what could  be the root cause of the problem?

`pi@raspberrypi:~/src/blinkt $ python3 tallyarbiter-pimoroni-blinkt-listener.py 192.168.178.46 4455`

> 
> Last Used Device Id: test1
> 
> Connected to Tally Arbiter server: 192.168.178.46 4455
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  True
> 255, 0, 0 -> red
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  True  mode_program:  False
> 0, 255, 0 -> green
> 0, 255, 0 -> green
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  True
> no colour
> 255, 0, 0 -> red
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  True  mode_program:  False
> 0, 255, 0 -> green
> 0, 255, 0 -> green
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  True
> no colour
> 255, 0, 0 -> red
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  False  mode_program:  False
> mode_preview:  True  mode_program:  False
> 0, 255, 0 -> green
> 0, 255, 0 -> green
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  True
> 255, 0, 0 -> red
> no colour
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  True  mode_program:  False
> no colour
> 0, 255, 0 -> green
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  True
> no colour
> 255, 0, 0 -> red
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [{'sourceId': 'TEST', 'address': 'TEST'}], 'linkedSources': [], 'active': True}
> mode_preview:  False  mode_program:  False
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  True  mode_program:  False
> 0, 255, 0 -> green
> 0, 255, 0 -> green
> ^CDisconnected from Tally Arbiter server: 192.168.178.46 4455
> device_states:  {'deviceId': '18155649', 'busId': 'e393251c', 'sources': [], 'linkedSources': [], 'active': False}
> device_states:  {'deviceId': '18155649', 'busId': '334e4eda', 'sources': [], 'linkedSources': [], 'active': False}
> mode_preview:  False  mode_program:  False
> no colour
> Exiting Tally Arbiter Listener.

**Comment by josephdadams** [comment]
I’m going to close this and re open it back in the other repo.
