### ISSUE TITLE
[Bug]: ATEM not working

### ISSUE THREAD

**Issue by lainol** [josephdadams/TallyArbiter#733]
### What happened?

ATEM source not working.

I have vMix and 2 Atem connected. vMix is working fine but atem not. 

Can see the log changing source but no change in device preview/progam state.

[9/12/24 3:36 PM] atem Bus: Program
[9/12/24 3:36 PM] atem Bus: Preview

### Version

3.1.0

### Distribution

Desktop

### OS

Windows

**Comment by josephdadams** [comment]
Did it work on v3.0.10?

**Comment by lainol** [comment]
> Did it work on v3.0.10?

Yes! I tested it in 3 pcs to be sure.

**Comment by josephdadams** [comment]
fixed in `v3.1.1`

**Comment by tetotaglia** [comment]
Is fixed also for Docker release?
I still have issues with Atem, only the last device work ( higher index)
