### ISSUE TITLE
ATEM mini extreme iso

### ISSUE THREAD

**Issue by ajvdmeij** [josephdadams/TallyArbiter#75]
Hi Joseph,

Thanks for all the great work. We (ate mu=y school) have recently purchased a ATEM mini extreme iso, with 8 inputs. Is the software compatible with this new machine. For all the inputs? I ask this because we want to make a tally system and want to purchase some MStick5C's.

Thanks in advance,

Arjan

**Comment by JTF4** [comment]
To my knowledge, as long as the instructions in the documentation are followed TallyArbiter should work with the ATEM Mini Extreme ISO.

**Comment by josephdadams** [comment]
Yes it is compatible. If you have a compatibility issue feel free to submit a bug report here.
