### ISSUE TITLE
GPO Listener hard crashing

### ISSUE THREAD

**Issue by lpcollier** [josephdadams/TallyArbiter#76]
I did an in-place upgrade on 7th April, and redid the configuration file for the GPO listener. Server and listener are running on a Raspberry Pi. It's connected to one ATEM 2M/E. It's been stable up until now with a pull from around September time, but I had some issues with the logic as I wanted one tally to cover several inputs on the ATEM. This is working great on the latest version, but despite being stable when testing it hard crashed multiple times in production on Sunday. 

`Attempting to connect to Tally Arbiter server:  {}:{} 127.0.0.1 4455`
`Unexpected error: <class 'ValueError'>`
`An error occurred internally.`
`Setting all GPOs to low before exiting.`

Any thoughts?

It would be good if the GPO listener was able to automatically attempt to reconnect rather than exiting, I was planning to take a look at the code and see if I could contribute this, but wondering if you have a quick fix for the hard crash in the meantime.

**Comment by josephdadams** [comment]
A valueerror in python is when a string can't convert to int, that sort of thing. Maybe something in the config file is incorrect?

**Comment by lpcollier** [comment]
Has there been any change in the messages passed from the server? I'm assuming the config file is parsed as soon as the listener is launched, whereas this error occurs minutes or even hours after launching the listener. However I will check the config file and see if there's an obvious error.

**Comment by josephdadams** [comment]
I don't recall changing anything in the messages being passed, but if you can nail it down to a specific commit where it stopped being reliable, I can take a look.
