### ISSUE TITLE
Direct log to device

### ISSUE THREAD

**Issue by kutuz00** [josephdadams/TallyArbiter#82]
Having issue to direct access to device. This I adding to address **/tally?deviceid=f06a3d41** 
looks like this: http://my-ip:4455/tally?deviceid=f06a3d41

**Comment by josephdadams** [comment]
What's the issue?

**Comment by kutuz00** [comment]
![Screen Shot 2021-05-02 at 10 30 50 AM](https://user-images.githubusercontent.com/36905691/116822048-a088d000-ab31-11eb-8408-417c5d33dabc.png)

I am trying to connect to a device directly but am unable to. Instead, it's taking me to the home page with camera section options.

**Comment by josephdadams** [comment]
Are you sure that's a valid DeviceId? Are you running TA 1.5.9? It works just fine for me over here. I tried it in multiple browsers.

**Comment by kutuz00** [comment]
Thanks for answer. Just finished update and now this feature work.

God Bless
