### ISSUE TITLE
trying to run tallyarbiter on raspberry pi 4 4gb npm install error

### ISSUE THREAD

**Issue by MikeXtremeLED** [josephdadams/TallyArbiter#83]
Hii,

I am trying to install tally arbiter on my raspberry pi 4.

Here are the steps that ive made ( be carefull, i am a level 1 beginner raspberry pi user :) 
;
*installing the standard things
sudo apt update

sudo apt install git

*then i am installing Nodejs 
wget https://nodejs.org/dist/v14.16.1/node-v14.16.1-linux-arm                                                                                                                                                                           v7l.tar.xz

ls
node-v14.16.1-linux-armv7l.tar.xz
tar -xf node-v14.16.1-linux-armv7l.tar.xz
ls
node-v14.16.1-linux-armv7l  node-v14.16.1-linux-armv7l.tar.xz
cd node-v14.16.1-linux-armv7l/
:~/node-v14.16.1-linux-armv7l $ sudo cp -R * /usr/local/
/node-v14.16.1-linux-armv7l $ cd ..
node -v
v14.16.1
npm -v
6.14.12
ls
node-v14.16.1-linux-armv7l  node-v14.16.1-linux-armv7l.tar.xz
rm -rf node-v14.16.1-linux-armv7l node-v14.16.1-linux-armv7l.tar.xz

* okay ive installed Nodejs so i gonna install now Tallyarbiter

sudo git clone https://github.com/josephdadams/tallyarbiter
ls
tallyarbiter
cd tallyarbiter/
/tallyarbiter $ sudo npm install
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated dgram@1.0.1: npm is holding this package for security reasons. As it's a core Node module, we will not transfer it over to other users. You may safely remove the package from your dependencies.

> @serialport/bindings@8.0.8 install /home/pi/tallyarbiter/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES current user ("pi") does not have permission to access the dev dir "/root/.cache/node-gyp/14.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/tallyarbiter/node_modules/@serialport/bindings/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/tallyarbiter/node_modules/@serialport/bindings/.node-gyp'
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/tallyarbiter/node_modules/@serialport/bindings
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN TallyArbiter@1.5.9 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@8.0.8 (node_modules/@serialport/bindings):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 180 packages from 136 contributors and audited 245 packages in 20.904s

7 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

*from that point i got a error that i am running a old version 

What is the best thing to do for fixing this?

Thanksss

**Comment by josephdadams** [comment]
Try running `sudo npm install --unsafe-perm` instead

**Comment by MikeXtremeLED** [comment]
the only thing that i have when i run the tally arbiter it says that i cannot find the config file.

pi@raspberrypi:~/tallyarbiter $ node index.js
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Loading the stored Tally Arbiter configuration file.
**_### [Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     The config file could not be found._**
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Source Setup Complete.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Initializing Device States.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Device States Initialized.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Setting up the REST API.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     REST API Setup Complete.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Starting socket.IO Setup.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Socket.IO Setup Complete.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Starting OSC Setup.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Starting VMix Emulation Service.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Starting HTTP Server.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     OSC Sending Port Ready. Broadcasting on Port: 5958
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Finished VMix Emulation Setup. Listening for VMix Tally Connections on TCP Port 8099.
[Mon May 10 2021 09:52:15 GMT+0100 (British Summer Time)]     Tally Arbiter running on port 4455
[Mon May 10 2021 09:52:16 GMT+0100 (British Summer Time)]     Listener Client Connected. Type: m5-stickc Device: Unassigned DeviceID: unassigned
[Mon May 10 2021 09:52:16 GMT+0100 (British Summer Time)]     Listener Client Connected. Type: m5-stickc Device: Unassigned DeviceID: unassigned

**Comment by josephdadams** [comment]
There is no config file until you set up your first source or device in TA. Then it is created.
