### ISSUE TITLE
Frontend rewrite using Angular

### ISSUE THREAD

**Issue by hrueger** [josephdadams/TallyArbiter#86]
Hi @josephdadams ,
This is such a cool project, I really like it. Thanks for creating it.

However, I found some things which could be improved (like missing help texts or bootstrap classes for input fields, chat issues on layout mobile devices, ...). I'd be happy to work on all that. 

But as the UI is already quite complex with elements constantly being created with HTML strings and then added to the DOM, I thought that maybe using a frontend framework would reduce complexity and improve maintainability of the code?

I'm personally quite familiar with Angular, so if I did a frontend rewrite using Angular, would you be interested in a PR?

**Comment by hrueger** [comment]
A second step could be rewriting the backend with TypeScript. This way we could create a class for each Source and get rid of all the switch-case logic.

**Comment by josephdadams** [comment]
Sure! Happy to have you contribute!
