### ISSUE TITLE
TypeError with GPO_Listener

### ISSUE THREAD

**Issue by JWandscheer** [josephdadams/TallyArbiter#9]
When trying to connect a client via the GPO_Listener or with a very simple own listener Client, the Server throws the following Exception: `TypeError: Cannot read property 'id' of undefined`. The stack says the Error occurs in Line 541, seems like  getDeviceByDeviceId() uses an undefined array of devices?
Connecting a Listener via Web Interface runs correctly.

**Comment by josephdadams** [comment]
This will be fixed in the next release! A workaround is to make sure to you are using a valid Device Id in your gpo config file.

**Comment by josephdadams** [comment]
This is fixed in the latest release, so please go and test that! If it's not fixed, you can re-open this.
