### ISSUE TITLE
Follow up for #50, Atem delay during transition

### ISSUE THREAD

**Issue by peterfdej** [josephdadams/TallyArbiter#98]
The red red during transition is okay now, but there is still a delay of around 5 sec.
https://drive.google.com/file/d/1DfXQE7UVrdI1NAbr8yyc9B7E4NjHc7Ku/view?usp=sharing

**Comment by JTF4** [comment]
Give the new version a try. We've done a lot of optimization that may help.

**Comment by peterfdej** [comment]
The latest version is much better. the delay is now less then 1 s. thx
